### DISCUSSION TITLE
What's gateway? Is that necessary?

### DISCUSSION THREAD

**Discussion by acgxv** [42wim/matterbridge#1597] [Help / Q&A] [answered]
The WIKI just told me how to configure it. But I don't what dose it use for.

**Comment by acgxv** [comment]
Okay. It's necessary.

```
[0000]  INFO main:         [setupLogger:matterbridge.go:106] Enabling debug logging.
[0000]  INFO main:         [main:matterbridge.go:46] Running version 1.22.3
[0000] FATAL main:         [main:matterbridge.go:68] Starting gateway failed: no [[gateway]] configured. See https://github.com/42wim/matterbridge/wiki/How-to-create-your-config for more info
```

**Comment by Mikaela** [comment, marked as answer]
Gateway is the room/channel/discussion you wish to bridge, everything that is bridged together is a gateway, you need one for each.

E.g.  to bridge two IRC channels together

```toml
[[gateway]]
name="test"
enable="true"

    [[gateway.inout]]
    account="irc.localergo"
    channel="#test"

    [[gateway.inout]]
    account="irc.liberachat"
    channel="#test"

[[gateway]]
name="secretchan"
enable=true

    [[gateway.inout]]
    account="irc.liberachat"
    channel="##secretchan+"

    [[gateway.inout]]
    account="irc.localergo"
    channel="#secretchan+"
```

I have a more complete example [in my gist repo](https://github.com/Mikaela/gist/blob/master/irc/matterbridge/matterbridge-example.toml)
