### DISCUSSION TITLE
Does discord bot displays as online?

### DISCUSSION THREAD

**Discussion by Syntoxr** [42wim/matterbridge#1892] [Help / Q&A] [answered]
Hi,
I'm currently trying to bridge between WhatsApp and discord. I've successfully built a WhatsApp multi-device docker image.
As nothing worked after configuring every thing, I started testing stuff. For now, I disabled the WA bridge and just tried to bridge between two discord channels on the same server, but without luck (logs say the bridge is joining both).
I noticed that I and the mee6 bot do show up as online, but my matter bridge bot doesn't. Is this right, or should I see it there?

Thanks 

```toml
[discord]
  [discord.test]
  #You can get your token by following the instructions on
  #https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
  #If you want roles/groups mentions to be shown with names instead of ID, 
  #you'll need to give your bot the "Manage Roles" permission.
  Token="1234567890qwertzuiopasdfghjklyxcvbnm" # BotToken
  Server="1234567890" #test server id
  RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
  AutoWebhooks=true


# this must always be [[gateway]], don't use anything else
[[gateway]]
name="gateway-test"
enable=true

  [[gateway.inout]]
  account="discord.test"
  channel="test" #also tried with ids

  [[gateway.inout]]
  account="discord.test"
  channel="general" #also tried with ids
```
