### DISCUSSION TITLE
Clarity about context of settings

### DISCUSSION THREAD

**Discussion by unode** [42wim/matterbridge#2066] [Help / Q&A]
Hello everyone,

We have a great wiki page [listing all the settings supported](https://github.com/42wim/matterbridge/wiki/Settings).
That page however doesn't mention in which context each setting is recognized.

Could someone clarify if all settings are acceptable and understood in all contexts?

Below some of the contexts I am referring to.
I'm not sure if all are actually valid. Clarification here would also be appreciated:

```toml
GLOBAL_CONTEXT

[general]
# general being a special tag according to [this](https://github.com/42wim/matterbridge/wiki/Settings#info)
GENERAL_CONTEXT

[mattermost]
    [mattermost.test]
    CONNECTION_CONTEXT

[[gateway]]
GATEWAY_CONTEXT
    [[gateway.inout]]
    account="mattermost.test"
    GATEWAY_CHANNEL_CONTEXT

```

To give an example, can `ShowJoinPart=true` be configured anywhere or only in `CONNECTION_CONTEXT` and only for some connection types?
Is it simply silently ignored if used in a context where it is not supported?
