### ISSUE TITLE
When there are multiple gateways, Discord messages don't get sent to Mattermost

### ISSUE THREAD

**Issue by steinbitglis** [42wim/matterbridge#1030]
**Describe the bug**
When the matterbridge is running and there are multiple gateways defined in the toml-file,
discord-messages don't show up at the other end (Mattermost for me).
[[samechannelgateway]] still works both ways, as long as there are no more than
one ordinary gateway. Otherwise, those channels all have the same issue.

Also, there's no way to use [[samechannelgateway]] with channels that reside in categories
in Discord.

**Environment (please complete the following information):**
 - OS: Debian 10.3
 - Matterbridge version: **1.16.5 4be00bbe**

**Additional context**

<details><summary>matterbridgeconfig.txt (<a href="https://github.com/42wim/matterbridge/files/4313814/matterbridgeconfig.txt">download</a>)</summary>

```toml
[discord.mydiscord]

# You can get your token by following the instructions on
# https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
# If you want roles/groups mentions to be shown with names instead of ID,
# you'll need to give your bot the "Manage Roles" permission.
Token="###########################################################"
Server="##########" # picked from guilds the bot is connected to
# UseUserName=true
RemoteNickFormat="*{NICK}*:\t"


[mattermost.mymattermost]
#The mattermost hostname. (do not prefix it with http or https)
Server="localhost:8065"

#the team name as can be seen in the mattermost webinterface URL
#in lowercase, without spaces
Team="######"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
Login="###########"
Password="####################"

RemoteNickFormat="*{NICK}*:\t"
PrefixMessagesWithNick=true

NoTLS=true

# this must always be [[gateway]], don't use anything else
[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="###########/###"

[[gateway.inout]]
account="mattermost.mymattermost"
channel="##############"

# this must always be [[gateway]], don't use anything else
[[gateway]]
name="gateway2"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="###############"

[[gateway.inout]]
account="mattermost.mymattermost"
channel="##############"
```

</details>
