### ISSUE TITLE
Long messages from Whatsapp cannot be sent to Slack

### ISSUE THREAD

**Issue by glazzara** [42wim/matterbridge#1081]
**Describe the bug**
Long messages from Whatsapp cannot be sent to Slack.
Note: it always works from Slack to Whatsapp.

**To Reproduce**
Send a 3000 characters long message from Whatsapp to Slack, it works
Send a 3001 characters long message from Whatsapp to Slack, it fails, nothing appears.

**Expected behavior**
Messages should be relayed and may be splitted into several ones.

**Screenshots/debug logs**
I get the following debug :

```
level=error msg="Failed to sent user message to Slack: &errors.errorString{s:"invalid_blocks"}" prefix=slack
level=error msg="SendMessage failed: invalid_blocks" prefix=gateway
```

**Environment (please complete the following information):**
 - OS: [e.g. linux]
 - Matterbridge version: output of  `matterbridge -version`
 - If self compiled: output of `git rev-parse HEAD`

Environment (please complete the following information):

OS: linux
Matterbridge version: 1.17.2 (official release)
Additional context
```toml
[general]
PreserveThreading=true
ShowUserTyping=true
ShowJoinPart=false
NoSendJoinPart=false
IgnoreNicks="XXXX"
IconURL="https://github.com/identicons/{NICK}.png"

MediaDownloadSize=50000000
MediaDownloadPath="/var/www/matterbridge"
MediaServerDownload="https://url"
MediaDownloadBlacklist=[".html$",".htm$", ".js$", ".css$", ".php$"]
verbose=true

[slack]
[slack.mine]
Token="xoxb-XXXXXXXXX"
RemoteNickFormat="{NICK}"
verbose=true

[whatsapp.mine]
Number="+33XXXXXX"
SessionFile="session-XXXXXXX.gob"
RemoteNickFormat="#{NICK} : "
verbose=true

[[gateway]]
enable=true

[[gateway.inout]]
account="whatsapp.mine"
channel="XXXXXXXXXX@g.us"

[[gateway.inout]]
account="slack.mine"
```
