### ISSUE TITLE
User Spoofing on file send from Mattermost to Slack

### ISSUE THREAD

**Issue by miasmaejuices** [42wim/matterbridge#1125]
**Describe the bug**

User Spoofing on file send - When sending a message from Mattermost to Slack, the Avatar & ID are spoofed correctly.  However, when sending a file in the same way, Slack does not spoof the Avatar & ID correctly, instead it posts the file with the ID/Avatar of the App/Bot.

**To Reproduce**

```
[mattermost.mymattermost]
Server="<server url>:443"
Team="<surname>-family"
Token="<login token>"
RemoteNickFormat="{NICK} - "
PrefixMessagesWithNick=false
WebhookURL="<mattermost incoming webhook>"

[slack]
[slack.myslack]
Token="<slack bot token>"
RemoteNickFormat="{NICK}"

...[snip]

[[gateway.inout]]
account="mattermost.mymattermost"
channel="<channel name>"

[[gateway.inout]]
account="slack.myslack"
channel="<channel name>"
```

**Expected behavior**

The expectation is that when displaying a message from a Mattermost User in Slack, it should spoof the Avatar/ID of the sender from Mattermost.

This happens only with normal messages, and seems to break when sending files to Slack from Mattermost.

**Screenshots/debug logs**

![Capture](https://user-images.githubusercontent.com/33153516/81032330-7f23e280-8ee3-11ea-82eb-dd08def40e03.JPG)

**Environment (please complete the following information):**
Docker Host
 - OS : Ubuntu 18.04 x86_64
 - 16Gb RAM

Mattermost
 - OS : Debian Buster armhf (Raspberry Pi - dedicated for Mattermost)
 - 2Gb RAM

**Additional context**
Using docker-compose as below:

```
  matterbridge:
    image: 42wim/matterbridge
    container_name: matterbridge
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
    - ${USERDIR}/docker/matterbridge/matterbridge.toml:/matterbridge.toml
```
