### ISSUE TITLE
Docker-compose container doesn't connect to IRC over IPv6 and times out

### ISSUE THREAD

**Issue by zejar** [42wim/matterbridge#1129]
**Describe the bug**
So I just stumbled onto this very strange issue. When I run the container using `docker run` the container gets an IPv6 address and can connect to IRC successfully, but when started using docker-compose it times out.

**To Reproduce**
The working docker run command is: `docker run -v /home/user/docker/matterbridge/matterbridge.toml:/matterbridge.toml 42wim/matterbridge -debug`
The compose file that times out:
```
version: '2.4'

services:        
  matterbridge:
    image: 42wim/matterbridge
    restart: unless-stopped
    container_name: matterbridge
    command: "-debug"
    volumes:
      - ${DOCKER_DIR}/matterbridge/matterbridge.toml:/matterbridge.toml
    networks:
      default:
        ipv6_address: 2001:db8:123:d008:4:455c:75c9:2818

networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 2001:db8:123:d008:4::/80
        gateway: 2001:db8:123:d008:4::1
```

After that `docker-compose up -d`.

**Expected behavior**
It is expected to connect to the IRC server as it would when run using `docker run`. It can also successfully connect to other sites using IPv6, I've ran this setup for a few years now with other containers.

**Screenshots/debug logs**
```
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.17.5-dev 52a071e3
[0000]  INFO main:         WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[0000]  INFO router:       Parsing gateway gateway1
[0000]  INFO router:       Starting bridge: irc.myirc
[0000]  INFO irc:          Connecting irc.snt.utwente.nl:6697
[0005] ERROR irc:          disconnect: error: dial tcp: i/o timeout
[0005] FATAL main:         Starting gateway failed: Bridge irc.myirc failed to start: connection failed dial tcp: i/o timeout
```

This timeout message appears fairly quick after starting the container. When running a tcpdump on the host I don't see any traffic going out to the IRC server, but I do see outgoing traffic to Telegram (the other protocol configured) and I also see dns requests for the Telegram API.

**Environment (please complete the following information):**
 - OS: Debian 10.3
 - Matterbridge version: 1.17.5-dev
 - If self compiled: output of `git rev-parse HEAD`

**Additional context**
```
[irc.myirc]
Nick="<nick>"
NickServNick="<nickname>"
NickServPassword="<password>"
Server="irc.snt.utwente.nl:6697"
UseTLS=true
UseSASL=true
SkipTLSVerify=false
RemoteNickFormat=""

[telegram.mytelegram]
Token="<token>"
RemoteNickFormat="<{NICK}> "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#<channel>"

[[gateway.inout]]
account="telegram.mytelegram"
channel="<channel>"
```
