### ISSUE TITLE
Discord chat function isnt actual chat.

### ISSUE THREAD

**Issue by dsk80004** [42wim/matterbridge#1194]
**Describe the bug**
When posting to discord it should be a chat message, although the issue with this is that it doesnt actually use chat responses.

**To Reproduce**
Connect matter bridge to a discord server with another bot which allows for communication with other bots, For instance any TTS Bot. https://top.gg/bot/513423712582762502 Here is a good example although most all tts bots will have this function. Then try bringing up it's -help command of setting it up at all to read the messages from the bridge. You will find that it doesnt do so, although if you have another bot which will say what you type in you can get it to work. Like when you mistype a command for the KDBot it returns an actual chat message pinging the person who tried to use it. that text ends up getting read. So one of the discord chat methods does not work with other bots instinctively. Either that of the matter bridge bot silences other bots it's self so they cant read it's messages. Although that's unlikely as I've seen other bots do the same.

**Expected behavior**
The idea would be to allow for text to speech for game servers, then in the future one might be able to add the earBot which does voice to test. That way players with hearing disorder would be able to be apart of team voice chats.

**Environment (please complete the following information):**
 - OS: Windows 10 64bit
 - Matterbridge version: 1.17.2 d97b077e

**Additional context**
```toml
[discord.discord]
Token=". . . ."
Server=". . . ." # picked from guilds the bot is connected to
RemoteNickFormat=""


[irc.irc]
    Server="127.0.0.1:6667"
    Nick="Discord"
    RemoteNickFormat="{NICK}: "

[[gateway]]
name="tes3mp-chat"
enable=true
    [[gateway.inout]]
    account="irc.irc"
    channel="#test"
    
```
