### ISSUE TITLE
User spoofing from Telegram to Mattermost

### ISSUE THREAD

**Issue by ret2libc** [42wim/matterbridge#1239]
**Describe the bug**
I'd like to see the messages coming from Telegram as if they are written directly by that user on mattermost.

**To Reproduce**
I send a message on Telegram and I see it on mattermost as coming from `@ret2libc`. However, when someone else who is not me sends a message on Telegram, I still see the message on mattermost as coming from `@ret2libc`. Is this because they don't have the same username on Telegram and IRC?

**Expected behavior**
Messages coming from user X on Telegram should appear on Mattermost as coming from `X` and not `matterbridebotname` nor `@ret2libc` (my username on mattermost).

**Screenshots/debug logs**
Parts of the logs:
```
[0063] DEBUG gateway:      [SendMessage:gateway/gateway.go:467] => see config.Message{Text:"TTREE(3)", Channel:"radareorg", Username:"jeisonwi", UserID:"xxxxxxxx", Avatar:"", Account:"telegram.mytelegram", Event:"", Protocol:"telegram", Gateway:"radareorg", ParentID:"", Timestamp:time.Time{wall:0xbfcefaa832a67315, ext:63725191255, loc:(*time.Location)(0x3447200)}, ID:"", Extra:map[string][]interface {}{}}     
[0063] DEBUG mattermost:   [handleMatterClient:bridge/mattermost/handlers.go:91] map[string]interface {}{"channel_display_name":"RadareOrg", "channel_name":"radareorg", "channel_type":"P", "post":"{\"id\":\"xxxxxxxx\",\"create_at\":1599828768889,\"update_at\":1599828768889,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"zzzzzzzzzzzz\",\"channel_id\":\"yyyyyyyyyy\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"TTREE(3)\",\"type\":\"\",\"props\":{\"from_webhook\":\"true\",\"matterbridge_btdn5ofvmcmk6kc73l90\":true,\"webhook_display_name\":\"matterbridge\"},\"hashtags\":\"\",\"pending_post_id\":\"\",\"reply_count\":0,\"metadata\":{}}", "sender_name":"@ret2libc", "set_online":true, "team_id":"xxxxxxxxxxxxx"}  
```

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: 1.18.4-dev
 - If self compiled: 91c58ec0271454105b5c66bcaa466c90464c7753

**Additional context**
```toml
[telegram.mytelegram]
Token="<mytoken>"
RemoteNickFormat="({PROTOCOL}) &lt;{NICK}&gt; "
MessageFormat="HTMLNick"

[mattermost.mymattermost]
Server="<myserver>:443"
Team="<myteam>"
Login="<botloginname>"
Token="<bottoken>"
RemoteNickFormat="{NICK}"
WebhookURL="<webhookincomingurl>"

[[gateway]]
name="<name>"
enable=true

        [[gateway.inout]]
        account="telegram.mytelegram"
        channel="<channel>"

        [[gateway.inout]]
        account="mattermost.mymattermost"
        channel="<channel>"
```
