### ISSUE TITLE
Starting gateway failed: dial tcp 127.0.0.1:8065: connect: connection refused

### ISSUE THREAD

**Issue by Farelkin** [42wim/matterbridge#1281]
### Environment

Version:

Operating system:
Ubuntu 18.04 LTS

Docker version:            19.03.13
Go version (in docker): go1.13.15
Mattermost docker image: mattermost-preview
Matterbridge docker image: 42wim/matterbridge

### Please describe the expected behavior.
Connect two accounts mattermost via matterbridge. Both accounts upped with docker, same to matterbridge.

### Please describe the actual behavior. 

matterbridge_1  | time="2020-11-02T11:14:06Z" level=info msg="Running version 1.19.1-dev 0d997666" prefix=main
matterbridge_1  | time="2020-11-02T11:14:06Z" level=info msg="WARNING: THIS IS A DEVELOPMENT VERSION. Things may break." prefix=main
matterbridge_1  | time="2020-11-02T11:14:06Z" level=info msg="Parsing gateway mygateway" prefix=router
matterbridge_1  | time="2020-11-02T11:14:06Z" level=info msg="Starting bridge: mattermost.bridge_user1 " prefix=router
matterbridge_1  | time="2020-11-02T11:14:06Z" level=info msg="Connecting using login/password (sending and receiving)" prefix=mattermost
matterbridge_1  | time="2020-11-02T11:14:06Z" level=info msg="Connecting user1_host1 (team: ) on 127.0.0.1:8065" prefix=mattermost
matterbridge_1  | time="2020-11-02T11:14:06Z" level=fatal msg="Starting gateway failed: Bridge mattermost.bridge_user1 failed to start: "http://127.0.0.1 :8065/api/v4/users/logout: model.client.connecting.app_error, Post http://127.0.0.1:8065/api/v4/users/logout: dial tcp 127.0.0.1:8065: connect: connectio n refused"" prefix=main

### Any steps to reproduce the behavior?
I tried to change ports, but it doesn have any effect

### Please add your configuration file 

**docker-compose config:**
```
version: '3.8'

volumes:
  pgdata:
    driver: local
services:
#-----------------mattermost host 1-----------------------
  mattermost-1:
    image: mattermost/mattermost-preview
    ports:
      - 8065:8065
#-----------------mattermost host 2-----------------------
  mattermost-2:
    image: mattermost/mattermost-preview
    ports:
      - 8066:8065
    depends_on:
      - mattermost-1
#-----------------mattermost host 3-----------------------
  mattermost-3:
    image: mattermost/mattermost-preview
    ports:
      - 8067:8065
      depends_on:
        - mattermost-2
#-----------------matterbridge-----------------------
  matterbridge:
    image: 42wim/matterbridge
    volumes:
      - type: bind
        source: ./matterbridge
        target: /etc/matterbridge
    depends_on:
      - mattermost-3
```

**matterbridge.toml**
```
[mattermost]
[mattermost.bridge_user1]
NoTLS = true

Server = "127.0.0.1:8065"
Login = "user1_host1"
Password = "user1_password"

Team = "rtk"

RemoteNickFormat = "[{PROTOCOL}] <{NICK}>"
PrefixMessagesWithNick = true

[mattermost.bridge_user2]
NoTLS = true

Server = "127.0.0.1:8066"
Login = "user1_host2"
Password = "user2_password"

Team = "rtk"

RemoteNickFormat = "[{PROTOCOL}] <{NICK}>"
PrefixMessagesWithNick = true

[mattermost.bridge_user3]
NoTLS = true

Server = "127.0.0.1:8067"
Login = "user1_host3"
Password = "user3_password"

#Team = "rtk"

RemoteNickFormat = "[{PROTOCOL}] <{NICK}>"
PrefixMessagesWithNick = true
[[gateway]]
name = "mygateway"
enable = true

[[gateway.inout]]
account = "mattermost.bridge_user1"
channel = "off-topic"

[[gateway.inout]]
account = "mattermost.bridge_user2"
channel = "off-topic"

[[gateway.inout]]
account = "mattermost.bridge_user3"
channel = "off-topic"

```
