### ISSUE TITLE
Bad default value for IRC Charset

### ISSUE THREAD

**Issue by lindhe** [42wim/matterbridge#1284]
**Describe the bug**
Without `Charset="utf-8"`, matterbridge will fail to recognize UTF-8 encoded characters and thus translate it incorrectly. It says in [matterbridge.toml.sample](https://github.com/42wim/matterbridge/blob/ae3bc3358b7339760ca0e6905d19905b298b671d/matterbridge.toml.sample#L38) that it will try to detect charset automatically if `Charset` is unset, but clearly it fails with the easiest case.

Interestingly, it is inconsistent with how it fails. I found that the string `åså` gets mangled while the string `åaå` works fine. I'm clueless as to why.

**To Reproduce**

1. Setup a bridge between IRC and Telegram like my config below.
2. Send the string `åså` to the IRC channel and see how it gets translated to `Ã¥sÃ¥` in Telegram.

**Expected behavior**
Either that the default charset is `utf-8` or that it's correctly detecting the charset.

**Screenshots/debug logs**
<img src="https://user-images.githubusercontent.com/7773090/98406443-402b4100-206e-11eb-99cf-4495fde559f6.png" alt="IRC" width="300px"/>
<img src="https://user-images.githubusercontent.com/7773090/98406439-3f92aa80-206e-11eb-8fb4-18d72f09c016.png" alt="Telegram" width="300px">

**Environment (please complete the following information):**
 - OS: linux (Docker)
 - Matterbridge version: `version: 1.19.1-dev 0d997666`

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))
```toml
[irc.test]
Server="irc.example.com:6697"
RemoteNickFormat="<tg-{NICK}> "
UseTLS=true
Nick="telegrambot"
Password="<my_nickserv_password>"

[telegram.test]
Token="<my_telegram_bot_token>"
RemoteNickFormat="&lt;{NICK}&gt; "
MessageFormat="HTMLNick"

[[gateway]]
name="test"
enable=true

[[gateway.inout]]
account="irc.test"
channel="#test"

[[gateway.inout]]
account="telegram.test"
channel="<negative_int_telegram_group_id>"
```
