### ISSUE TITLE
Starting gatweay failed ... read: connection refused

### ISSUE THREAD

**Issue by gabrc52** [42wim/matterbridge#1318]
**Describe the bug**
I'm getting connection errors when trying to run matterbridge on my Android arm64 phone (more details below).

**Steps To Reproduce**
Run matterbridge with the given setup on an Android arm64 phone (more details below).

**Expected behavior**
I'm getting the following connection errors when trying to run matterbridge on my arm64 phone.

**Screenshots/debug logs**
```
time="2020-11-30T07:32:33Z" level=info msg="Enabling debug logging." func=setupLogger file="matterbridge.go:106" prefix=main
time="2020-11-30T07:32:33Z" level=info msg="Running version 1.20.0 1a5353d7" func=main file="matterbridge.go:46" prefix=main
time="2020-11-30T07:32:33Z" level=debug msg="Configuring Discord Incoming Webhook" func=New file="bridge/discord/discord.go:45" prefix=discord
time="2020-11-30T07:32:33Z" level=info msg="Parsing gateway gw" func=Start file="gateway/router.go:66" prefix=router
time="2020-11-30T07:32:33Z" level=info msg="Starting bridge: discord.ccn " func=Start file="gateway/router.go:75" prefix=router
time="2020-11-30T07:32:33Z" level=info msg=Connecting func=Connect file="bridge/discord/discord.go:55" prefix=discord
time="2020-11-30T07:32:33Z" level=info msg="Connecting using webhookurl (for posting) and token" func=Connect file="bridge/discord/discord.go:59" prefix=discord
time="2020-11-30T07:32:33Z" level=info msg="Connection succeeded" func=Connect file="bridge/discord/discord.go:73" prefix=discord
time="2020-11-30T07:32:33Z" level=fatal msg="Starting gateway failed: Bridge discord.ccn failed to start: Get "https://discord.com/api/v6/gateway": dial tcp: lookup discord.com on [::1]:53: read udp [::1]:40941->[::1]:53: read: connection refused" func=main file="matterbridge.go:68" prefix=main
```

Sometimes, the errors are on a Telegram URL instead of a Discord URL, but it never successfully starts.

**Environment (please complete the following information):**
 - OS: Linux 4.14.117-perf+ #1 SMP PREEMPT aarch64 Android 10
 - Matterbridge version: 1.20.0 1a5353d7

Works fine on Linux 64 bit 1.20.0 1a5353d7

**Additional context**
`matterbridge.toml` 

```toml
[discord.ccn]
Token="blah"
Server="blah"
RemoteNickFormat="{NICK} desde {PROTOCOL} "
WebhookURL="https://discord.com/api/webhooks/blah/blah"

[telegram.prueba]
Token="blah"
RemoteNickFormat="<b>[{PROTOCOL}] &lt;{NICK}&gt; </b>"
MessageFormat="HTMLNick"

[[gateway]]
name="gw"
enable=true

[[gateway.inout]]
account = "discord.ccn"
channel = "prueba"

[[gateway.inout]]
account = "telegram.prueba"
channel = blah
```
