### ISSUE TITLE
Slack: Gateway start failure as the bridge can't join the channel

### ISSUE THREAD

**Issue by sdurrheimer** [42wim/matterbridge#1397]
**Describe the bug**
I've been trying to bridge a Slack channel with a Zulip stream.
I don't have issues with the Zulip part so far, but on the Slack side it seems problematic.
I make sure to follow the [wiki doc](https://github.com/42wim/matterbridge/wiki/Slack-bot-setup#create-the-classic-slack-app) and this [issue](https://github.com/42wim/matterbridge/issues/964#issuecomment-607629250), but matterbridge is complaining it can't join the channel:

```
Starting gateway failed: Bridge slack.cycloid failed to join channel: could not join channel: &errors.errorString{s:"channel #matterbridge-test not found"}
```

The Slack App bot user has already been invited to the channel tho:
![image](https://user-images.githubusercontent.com/1931038/107519948-27708100-6bb1-11eb-9466-402c49f89ea2.png)

Does someone has been following the installation steps recently and was able to make it work?

**To Reproduce**
Setup a new Slack-to-something bridge following the [documented steps](https://github.com/42wim/matterbridge/wiki/Slack-bot-setup#issues).

The Slack App interface changed a bit, there is no longer a `Bot users` menu.
The boot needs to be added via the `App Home` menu:
![image](https://user-images.githubusercontent.com/1931038/107518752-aa90d780-6baf-11eb-8ee1-875977cb33c6.png)

**Expected behavior**
Have the gateway working.
The Slack App bot user is already in the channel, it shouldn't try to join it.

**Screenshots/debug logs**
```
time="2021-02-10T13:50:10Z" level=info msg="Enabling debug logging." func=setupLogger file="matterbridge.go:106" prefix=main
time="2021-02-10T13:50:10Z" level=info msg="Running version 1.22.0 afcd362c" func=main file="matterbridge.go:46" prefix=main
time="2021-02-10T13:50:10Z" level=info msg="Parsing gateway cycloid-cycloid" func=Start file="gateway/router.go:66" prefix=router
time="2021-02-10T13:50:10Z" level=info msg="Starting bridge: slack.cycloid " func=Start file="gateway/router.go:75" prefix=router
time="2021-02-10T13:50:10Z" level=info msg="Connecting using token" func=Connect file="bridge/slack/slack.go:109" prefix=slack
time="2021-02-10T13:50:10Z" level=info msg="slack.cycloid: joining #matterbridge-test (ID: #matterbridge-testslack.cycloid)" func=joinChannels file="bridge/bridge.go:77" prefix=slack
time="2021-02-10T13:50:10Z" level=debug msg="Choosing token based receiving" func=handleSlack file="bridge/slack/handlers.go:23" prefix=slack
time="2021-02-10T13:50:10Z" level=debug msg="== Receiving event &slack.ConnectingEvent{Attempt:1, ConnectionCount:0}" func=handleSlackClient file="bridge/slack/handlers.go:52" prefix=slack
time="2021-02-10T13:50:11Z" level=debug msg="== Receiving event &slack.ConnectedEvent{ConnectionCount:0, Info:(*slack.Info)(0xc000278000)}" func=handleSlackClient file="bridge/slack/handlers.go:52" prefix=slack
time="2021-02-10T13:50:11Z" level=fatal msg="Starting gateway failed: Bridge slack.cycloid failed to join channel: could not join channel: &errors.errorString{s:"channel #matterbridge-test not found"}" func=main file="matterbridge.go:68" prefix=main
stream closed
```

**Environment (please complete the following information):**
Docker image running on K8s:
```
version: 1.22.0 afcd362c
```

**Additional context**

matterbridge.toml
```toml
[slack]
    [slack.cycloid]
    Token="<hidden>"

[zulip]
    [zulip.cycloid-service]
    Login="<hidden>"
    Token="<hidden>"
    Server="<hidden>"

[[gateway]]
name="cycloid-cycloid"
enable=true
    [[gateway.inout]]
    account="slack.cycloid"
    channel="#matterbridge-test"

    [[gateway.inout]]
    account="zulip.cycloid-service"
    channel="matterbridge-test/topic:bridge"
```

Slack App OAuth Scopes:
![image](https://user-images.githubusercontent.com/1931038/107519163-36a2ff00-6bb0-11eb-8e4a-fcc3a3370b34.png)
