### ISSUE TITLE
Bot tries to reupload attachment and fails, instead of simply showing the existing link

### ISSUE THREAD

**Issue by DarthGandalf** [42wim/matterbridge#1456]
**Describe the bug**
Source message in matrix (via t2bot discord/matrix bridge):
```
{
  "content": {
    "body": "output.mp4",
    "external_url": "https://cdn.discordapp.com/attachments/111111111111111/2222222222222/output.mp4",
    "info": {
      "h": 1080,
      "mimetype": "video/mp4",
      "size": 3709681,
      "w": 1920
    },
    "msgtype": "m.video",
    "url": "mxc://t2bot.io/fffffffffffffffffffffffffffffffff"
  },
  "event_id": "$111111111111RWbfl:t2bot.io",
  "origin_server_ts": 11111111111111,
  "sender": "@_discord_111111111111111:t2bot.io",
  "type": "m.room.message",
  "unsigned": {
    "age": 19527860
  },
  "room_id": "!XXXXXXX:matrix.org"
}
```
How it's shown on IRC:
`<relaybot> <system> file output.mp4 too big to download (3709681 > allowed size: 1000000)`

It should just show the existing link from `external_url` attribute

**To Reproduce**
1. Setup matrix room and discord channel, bridge them via t2bot.io
2. Setup matterbridge to bridge that matrix room with an IRC channel
3. Attach a big video from discord side

**Expected behavior**
Don't try to reupload anything. Just show the original external_url

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

**Environment (please complete the following information):**
 - OS: Linux 5.4.64
 - Matterbridge version:  from docker, `42wim/matterbridge:latest`, `1.22.1 b979aff2`
 - If self compiled: output of `git rev-parse HEAD`

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

```toml
[irc]
	[irc.xxx]
	Server="irc.freenode.net:6697"
	UseTLS=true
	UseSASL=true
	SkipTLSVerify=false
	Nick="..."
	NickServNick="..."
	NickServPassword="..."
	RemoteNickFormat="<{NOPINGNICK}> "
	MessageSplit=true
	ColorNicks=true

[matrix]
	[matrix.xxx]
	Server="https://matrix.org"
	Login="..."
	Password="..."
	NoHomeServerSuffix=true
	RemoteNickFormat="<{NOPINGNICK}> "
	HTMLDisable=true
	ColorNicks=true

[[gateway]]
name="bridge"
enable=true

	[[gateway.inout]]
	account = "irc.xxx"
	channel = "#...."

	[[gateway.inout]]
	account = "matrix.xxxx"
	channel = "#....:matrix.org"

```
