### ISSUE TITLE
IRC MessageLength setting has no effect

### ISSUE THREAD

**Issue by alvinhochun** [42wim/matterbridge#1540]
**Describe the bug**

IRC messages are truncated somewhere but not according to the [MessageLength](https://github.com/42wim/matterbridge/wiki/Settings#messagelength) setting and the `<message clipped>` string is not appended.

**To Reproduce**

1. Set MessageLength or use the default 400
2. Send a long message from another chat and observe the relayed message on the IRC end

**Expected behavior**

The message should be truncated by MessageLength and the message should end in `<message clipped>`.

**Screenshots/debug logs**

Log from my test (with MessageLength=100):
![圖片](https://user-images.githubusercontent.com/2397650/124440055-c2f6ce00-ddac-11eb-82fe-018958c7e4d2.png)

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: 1.22.3 e45bbe45

**Additional context**

```toml
[irc.liberachat]
Nick="x"
NickServNick="x"
NickServPassword="x"
Server="irc.libera.chat:6697"
UseTLS=true
UseSASL=true
SkipTLSVerify=false
RemoteNickFormat="[轉自{PROTOCOL}] <{NICK}> "
ShowJoinPart=true
MessageLength=100
MessageSplit=false

[matrix.x]
Server="x"
Login="x"
Password="x"
RemoteNickFormat="[轉自{PROTOCOL}] <{NICK}> "
NoHomeServerSuffix=false
ShowJoinPart=true


[[gateway]]
name="x"
enable=true

[[gateway.inout]]
account="irc.liberachat"
channel="##x"

[[gateway.inout]]
account="matrix.x"
channel="#x:x.x"
```
