### ISSUE TITLE
Avatar spoofing not working with Slack when following documentation

### ISSUE THREAD

**Issue by KidA001** [42wim/matterbridge#1556]
**Describe the bug**
With a local mediaserver setup and validated along with webhooks enabled, avatars are not being displayed from Telegram to Slack.

My `matterbridge.toml`

```toml
[general]
MediaDownloadPath="/var/www/matterbridge"
MediaServerDownload="http://{redacted}/media"

[slack]
[slack.collidervc]
RemoteNickFormat="{LABEL} | @{NICK}"
MessageSplit=true
WebhookUrl="secret-in-env-file"
Debug="true"

[telegram.Telegram]
Token="secret-in-env-file"
RemoteNickFormat="({PROTOCOL}) {NICK} "
MessageFormat="HTMLNick"
EditSuffix=" (edited)"
Label="Telegram | Testing Relay"
MessageSplit=true

[[gateway]]
name="gateway1"
enable=true

[[gateway.in]]
account="telegram.Telegram"
channel="-572179530"

[[gateway.out]]
account="slack.collidervc"
channel="collider-bot-testing"
```

I have validated that avatar PNGs are being downloaded to `/var/www/matterbridge` and I have also validated that they are publicly available from the `MediaServerDownload` url.

Here are my logs from matterbridge which show the dowload is successful but `Avatar` is still empty
```
time="2021-07-27T10:45:06Z" level=debug msg="Trying to download "1843720526.png" with size 3373" func=HandleDownloadSize file="bridge/helper/helper.go:159" prefix=telegram
time="2021-07-27T10:45:06Z" level=debug msg="Download OK "1843720526.png" 3373" func=HandleDownloadData file="bridge/helper/helper.go:175" prefix=telegram
time="2021-07-27T10:45:06Z" level=debug msg="<= Sending message from Collider on telegram.Telegram to gateway" func=handleRecv file="bridge/telegram/handlers.go:173" prefix=telegram
time="2021-07-27T10:45:06Z" level=debug msg="<= Message is config.Message{Text:"test", Channel:"-572179530", Username:"Collider", UserID:"1843720526", Avatar:"", Account:"telegram.Telegram", Event:"", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"80", Extra:map[string][]interface {}{}}" func=handleRecv file="bridge/telegram/handlers.go:174" prefix=telegram
time="2021-07-27T10:45:06Z" level=debug msg="mediaserver path placing file: /var/www/matterbridge/bb735cc0/1843720526.png" func=handleFilesLocal file="gateway/handlers.go:158" prefix=gateway
time="2021-07-27T10:45:06Z" level=debug msg="mediaserver download URL = http://{redacted}/media/bb735cc0/1843720526.png" func=handleFiles file="gateway/handlers.go:112" prefix=gateway
time="2021-07-27T10:45:06Z" level=debug msg="=> Sending config.Message{Text:"test", Channel:"-572179530", Username:"Collider", UserID:"1843720526", Avatar:"", Account:"telegram.Telegram", Event:"", Protocol:"telegram", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03816cc8ef21770, ext:487920212311, loc:(*time.Location)(0x339f980)}, ID:"80", Extra:map[string][]interface {}{}} from telegram.Telegram (-572179530) to slack.collidervc (collider-bot-testing)" func=SendMessage file="gateway/gateway.go:479" prefix=gateway
time="2021-07-27T10:45:06Z" level=debug msg="=> Receiving config.Message{Text:"test", Channel:"collider-bot-testing", Username:"Telegram | Testing Relay | @Collider", UserID:"1843720526", Avatar:"", Account:"telegram.Telegram", Event:"", Protocol:"telegram", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xc03816cc8ef21770, ext:487920212311, loc:(*time.Location)(0x339f980)}, ID:"", Extra:map[string][]interface {}{}}" func=Send file="bridge/slack/slack.go:195" prefix=slack
time="2021-07-27T10:45:06Z" level=debug msg="=> Send from telegram.Telegram (-572179530) to slack.collidervc (collider-bot-testing) took 260.931679ms" func=func1 file="gateway/gateway.go:488" prefix=gateway
```

I have sent multiple chats from different users to wait for the avatar to download, but still nothing is displayed

I'm also a bit confused as per [slacks documentation](https://api.slack.com/messaging/webhooks): `You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.`

**To Reproduce**
Steps to reproduce the behavior: use setup as above

**Expected behavior**
Avatar to display from Telegram to Slack when Mediaserver is present

**Screenshots/debug logs**
See above

**Environment (please complete the following information):**
 - OS: Running matterbridge via docker on a Linux VM
 - Matterbridge version:  `1.22.4-dev da4dcec1`
