### ISSUE TITLE
Slack display name does not update

### ISSUE THREAD

**Issue by keenan-v1** [42wim/matterbridge#1600]
**Describe the bug**
Matterbridge does not seem to pick up on Slack display name changes without stopping and restarting.

**To Reproduce**
Set up a Slack <-> IRC gateway, chat once. Change your display name on Slack. Chat again.

**Expected behavior**
I expect it to pull the latest display name.

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: 1.22.3 e45bbe45

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))
```toml
[irc]
    [irc.rizon]
    Server="irc.rizon.net:6697"
    Nick="SlackBot"
    NickServNick="SlackBot"
    NickServePassword="MyPass"
    UseTLS=true
    SkipTLSVerify=false
    RunCommands=["PRIVMSG nickserv :IDENTIFY MyPass SlackBot"]
    RemoteNickFormat="<{NICK}> "

[slack]
    [slack.myslack]
    Token="xoxb-secrets"
    RemoteNickFormat="<{NICK}> "
    PrefixMessagesWithNick=true


[[gateway]]
name="mychan"
enable=true
    [[gateway.inout]]
    account="irc.rizon"
    channel="#mychan"
    options = { key="withkey" }

    [[gateway.inout]]
    account="slack.myslack"
    channel="mychan"
```
