### ISSUE TITLE
Slack external channel messages with attachment not received

### ISSUE THREAD

**Issue by ahmr88** [42wim/matterbridge#1646]
**Describe the bug**
Slack messages with file attachments in external channels have empty URL fields.

**To Reproduce**
1. Create a shared channel on slack.
2. Setup gateway.inout on the external channel.
3. Send a message containing an attachment

**Expected behavior**
Messages with attachment should contain a valid url to the attachment.

**Screenshots/debug logs**
![2021-12-03-185905_3811x106](https://user-images.githubusercontent.com/44954417/144659998-012a075f-b45b-4546-bebe-af68c6f0f3d3.png)
![2021-12-03-190347_1898x883](https://user-images.githubusercontent.com/44954417/144660014-b17b3db7-4189-4260-8ce4-a07ca213fbfa.png)

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: `version: 1.23.3-dev`

**Additional context**
```toml
[slack]
[slack.mybridge]
Token="***"
RemoteNickFormat="@{NICK} - Discord Bot"

[discord]
[discord.mybridge]
Token="***"
Server="Some server"
RemoteNickFormat="[{PROTOCOL}] {NICK}:"

[[gateway]]
    name = "mygateway"
    enable=true

    [[gateway.inout]]
    account = "discord.mybridge"
    channel="test-channel"

    [[gateway.inout]]
    account ="slack.mybridge"
    channel = "external-test-channel"
```
