### ISSUE TITLE
samechannelgateway with irc and discord cannot find channelnames

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#173]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 0.12.0 8c7549a

### Please describe the expected behavior.

using the `[[samechannelgateway]]` configuration for bridging irc and discord
```toml
[[samechannelgateway]]
#REQUIRED and UNIQUE
name="bridge"
enable=true
   accounts = [ "irc.esper", "discord.chat" ]
   channels = [ "channelname" ]
```
i expected it to join `channelname` on discord and `#channelname` on irc

#### Use logs from running ```matterbridge -debug``` if possible.

it fails to join either `channelname` on irc or `#channelname` on discord

I suspect this will happen between any APIs that have a required prefix and those that not

#### (be sure to exclude or anonymize private data (tokens/passwords))

```toml
[irc]
    [irc.esper]
    Server="irc.esper.net:6697"
    Nick="bridgebotname"
    
    UseTLS=true
    UseSASL=true

    NickServNick="username"
    NickServPassword="hunter2"

    IgnoreNicks="cord spammer"

[discord]
    [discord.chat]
    Token="token"
    Server="servername"
    EditDisable=false
    EditSuffix=" (edited)"
    IgnoreNicks="[cord] spammer"
    RemoteNickFormat="<{NICK}> "
    ShowJoinPart=false

[[samechannelgateway]]
#REQUIRED and UNIQUE
name="bridge"
enable=true
   accounts = [ "irc.esper", "discord.chat" ]
   channels = [ "channelname" ]

# working configuration
# [[gateway]]
# #REQUIRED and UNIQUE
# name="channelname"
# enable=true
#     [[gateway.inout]]
#     account="irc.esper"
#     channel="#channelname"

#     [[gateway.inout]]
#     account="discord.chat"
#     channel="channelname"
```
