### ISSUE TITLE
discord channel mentions show up as long ids on irc

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#174]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 0.12.0 8c7549a

### Please describe the expected behavior.
from discord: ![channel-mention](https://i.imgur.com/3DbIxy5.png) 
on irc: `ruby_: <Λı> #cord`

### Please describe the actual behavior. 

the channel id is inserted instead of the readable name
irc: ![channel_id](https://i.imgur.com/DuO1uQW.png)

#### (be sure to exclude or anonymize private data (tokens/passwords))

```toml
[irc]
    [irc.esper]
    Server="irc.esper.net:6697"
    Nick="ruby" #effectively "ruby_" while testing
    
    UseTLS=true
    UseSASL=true

    NickServNick="username"
    NickServPassword="hunter2"

    IgnoreNicks="cord spammer"

[discord]
    [discord.chat]
    Token="token"
    Server="servername"
    EditDisable=false
    EditSuffix=" (edited)"
    IgnoreNicks="[cord] spammer"
    RemoteNickFormat="<{NICK}> "
    ShowJoinPart=false

[[gateway]]
#REQUIRED and UNIQUE
name="cord"
enable=true
    [[gateway.inout]]
    account="irc.esper"
    channel="#cord"

    [[gateway.inout]]
    account="discord.chat"
    channel="cord"
```
