### ISSUE TITLE
insert zero width space in nicks on irc

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#175]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 0.12.0 8c7549a

### Please describe the expected behavior.

prefixed nicknames on irc should have a no ping character or zero width space ` U+200B`

in the following line a zero width space is inserted at position 1 of the nickname
`<N​ickname> some message`

### Please describe the actual behavior. 

there is no inserted zwsp and there seem to be no options to enable such behaviour

#### (be sure to exclude or anonymize private data (tokens/passwords))

```toml
[irc]
    [irc.esper]
    Server="irc.esper.net:6697"
    Nick="ruby" #effectively "ruby_" while testing
    
    UseTLS=true
    UseSASL=true

    NickServNick="username"
    NickServPassword="hunter2"

    IgnoreNicks="cord spammer"

[discord]
    [discord.chat]
    Token="token"
    Server="servername"
    EditDisable=false
    EditSuffix=" (edited)"
    IgnoreNicks="[cord] spammer"
    RemoteNickFormat="<{NICK}> "
    ShowJoinPart=false

[[gateway]]
#REQUIRED and UNIQUE
name="cord"
enable=true
    [[gateway.inout]]
    account="irc.esper"
    channel="#cord"

    [[gateway.inout]]
    account="discord.chat"
    channel="cord"
```
