### ISSUE TITLE
slack-telegram bridge only works one way

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#178]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 0.12.1 
87229bab13d89d87284993f27a4c5c2afa762aa2

### Please describe the expected behavior.
bidirectional bridge between telegram and slack

### Please describe the actual behavior. 
messages from slack to telegram are sent, but messages from telegram are not picked up and do not appear in the debug log

#### (be sure to exclude or anonymize private data (tokens/passwords))

```toml

[slack]
    [slack.uni]

    useAPI=true
    Token="token"

    RemoteNickFormat="{NICK}"

[telegram]
    [telegram.uni]
    #REQUIRED
    Token="token"
    UseFirstName=false
    EditDisable=false

    EditSuffix=" (edited)"
    IgnoreNicks="spammer1 spammer2"
    ShowJoinPart=false
    
    RemoteNickFormat="<{NICK}> "

[[gateway]]
#REQUIRED and UNIQUE
name="organization"
enable=true
    [[gateway.inout]]
    account="slack.uni"
    channel="general" #general

    [[gateway.inout]]
    account="telegram.uni"
    channel="-10010715xxxxx"

[[gateway]]
#REQUIRED and UNIQUE
name="chat"
enable=true
    [[gateway.inout]]
    account="slack.uni"
    channel="random"

    [[gateway.inout]]
    account="telegram.uni"
    channel="-167837xxx"

```
