### ISSUE TITLE
Discord: username spoofing failed when a Telegram message followed a thread

### ISSUE THREAD

**Issue by jx11r** [42wim/matterbridge#1799]
**Describe the bug**
Just the username/avatar spoofing doesn't work when someone replies from Telegram in a thread.

**To Reproduce**
1. Enable PreserveThreading on both.
2. Send a message from Discord.
3. Reply that message on Telegram in a thread.

**Expected behavior**
Username/spoofing works properly on Discord.

**Screenshots/debug logs**
![image](https://user-images.githubusercontent.com/78786202/162353117-568f2780-9a9d-437d-a529-7df6af96d477.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Matterbridge version: 1.25.0

**Additional context**
```toml
[discord]
  [discord.testing]
    Token="my.discord.token"
    Server="my.server.id"
    RemoteNickFormat="{NICK}"
    UseLocalAvatar=["irc", "telegram"]
    AutoWebhooks=true
    PreserveThreading=true
    EditDisable=true

[telegram]
  [telegram.testing]
    Token="my.telegram.token"
    RemoteNickFormat="<{NICK}> "
    PreserveThreading=true
    EditDisable=true
    QuoteDisable=true
```
