### ISSUE TITLE
Feature Request: API select which gateway to send/reply to

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#189]
### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 0.13.1-dev

### Please describe the expected behavior.

POSTing to /api/message with a `channel` or `gateway` value in the json blob should send it there

### Please describe the actual behavior. 

when sending messages to the api using POST it always ends up in the gateway named api
it seems the gateway name is currently hardcoded here https://github.com/42wim/matterbridge/blob/master/bridge/api/api.go#L76

It might be also necessary to include the channel name AND gateway name in the messages, currently there is only the channel name
eg: 
gateway name = "api"
channel = "test-bridge" on discord
only "channel": "test-bridge" is currently available in messages

**Comment by 42wim** [comment]
That's by design.

The api should be seen as a bridge like irc or discord.

So if you sent a message to the "api" bridge it will be sent to the other bridges you have defined in your gateway.

In the example below it will be sent to the defined channels in irc, discord and slack

```
[[gateway]]
    name = "mygateway"
    enable=true

    [[gateway.inout]]
    account = "irc.freenode"
    channel = "#testing"

    [[gateway.inout]]
    account = "discord.test"
    channel = "general"

    [[gateway.inout]]
    account="api.local"
    channel="api"

    [[gateway.inout]]
    account="slack.test"
    channel="testing"
```

**Comment by NikkyAI** [comment]
so i have to have a seperate prot for every gatway i want to add a api channel to ?
my usecase is similar but with three channels in which i want to use the api. and sending a command to the bot listening on the api lets the bot respond to it on a different gateway

**Comment by NikkyAI** [comment]
```toml
[[gateway]]
name="test"
enable=true
    [[gateway.inout]]
    account="discord.teamdev"
    channel="bridge-test"

    [[gateway.inout]]
    account="api.local"
    channel="api"

[[gateway]]
name="test2"
enable=true
    [[gateway.inout]]
    account="discord.teamdev"
    channel="bridge-test2"

    [[gateway.inout]]
    account="api.local"
    channel="api2"
```
in this configuration i listen to gateway: test2 and send a message like this
```json
{'text': "running test command, args: ['1', '2']\n", 'channel': 'bridge-test2', 'username': 'cord', 'gateway': 'test2'}
```
which ends up in the `test` gateway.. not `test2`
