### ISSUE TITLE
Georgian letters are being cut when spoofing username in Discord

### ISSUE THREAD

**Issue by overflowz** [42wim/matterbridge#1911]
**Describe the bug**
When using a Slack -> Discord bridge and AutoWebhooks set to true, usernames with Georgian letters are cut in Discord only, but not in Slack (Discord -> Slack). This only happens on username spoofing. If RemoteNickFormat is being used, then it works as expected.

**To Reproduce**
Create a slack account, set Full Name & Display Name to აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰ (or just pick whatever letter and repeat so you can figure out where the cut happens), enable AutoWebhooks in Discord, write something in slack (in discord, you should see a spoofed username, but missing letters. The amount missing is random).

**Expected behavior**
It should not cut any letters.

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.
![image](https://user-images.githubusercontent.com/7758774/200116358-cd4b4264-3942-458b-847f-ac41523596bb.png)
![image](https://user-images.githubusercontent.com/7758774/200116364-15a845d7-bd64-4d35-b124-b195c60a73e3.png)

**Environment (please complete the following information):**
docker image: https://hub.docker.com/layers/42wim/matterbridge/latest/images/sha256-60f20397a461f426295e4f9bc2dc55339b1e899e17564e9c0ba59a2f4cf02e8f?context=explore

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))
```toml
[slack]
[slack.xxx]
PrefixMessagesWithNick=false
PreserveThreading=true
UseFullName=true

[discord]
[discord.xxx]
AutoWebhooks=true
PreserveThreading=true

[general]
RemoteNickFormat="[{PROTOCOL}] {NICK} " #also tried with NOPINGNICK
```
