### ISSUE TITLE
POST to api fails, but responds with OK

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#194]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 0.13.1-dev

### Please describe the expected behavior.
```
curl -X POST \
  http://localhost:4242/api/message \
  -H 'content-type: application/json' \
  -d '{"text": "test", "username": "somebot", "gateway": "ruby"}'
```
should send to the specified gateway, this worked before when i tested it for #189

### Please describe the actual behavior. 
it responds with 200 (OK) but nothing appears on the connected channels,
no matter what is used for the value of gateway, i tested with gateway="api" too, no success as expected
```
DEBU[2017-06-13T20:11:23+02:00] Sending message from somebot on api to gateway  module
=api
```

#### (be sure to exclude or anonymize private data (tokens/passwords))
```toml
[[gateway]]
name="ruby"
enable=true
    [[gateway.inout]]
    account="irc.esper"
    channel="#ruby"

    [[gateway.inout]]
    account="discord.obsidian"
    channel="ruby"

    [[gateway.inout]]
    account="api.local"
    channel="ruby"
```

**Comment by NikkyAI** [comment]
and with the same settings i can GET from api/messages just fine, with token enabled or on a server, no problem

**Comment by 42wim** [comment]
no messages after  ?
```
DEBU[2017-06-13T20:11:23+02:00] Sending message from somebot on api to gateway  module
=api
```

**Comment by NikkyAI** [comment]
no more messages and the bot takes the gateway the messages comes from and uses it to send back
using curl or postman i am also sure there were no typos.. most likely

**Comment by NikkyAI** [comment]
there also seems to be problem on that configuration where it can only send to discord..

```
DEBU[2017-06-14T00:37:38+02:00] Sending message from Nikky on discord.obsidian to gateway  module=discord            
DEBU[2017-06-14T00:37:38+02:00] empty channel
DEBU[2017-06-14T00:37:38+02:00] empty channel
DEBU[2017-06-14T00:37:38+02:00] empty channel
DEBU[2017-06-14T00:37:45+02:00] Sending message from Nikky on discord.obsidian to gateway  module=discord
DEBU[2017-06-14T00:37:45+02:00] empty channel
DEBU[2017-06-14T00:37:45+02:00] empty channel
DEBU[2017-06-14T00:37:45+02:00] empty channel
```

i tried to send two messages.. other log entries were from later messages on other platforms
maybe this has to with the borked gateway ?

**Comment by NikkyAI** [comment]
these settings work
```toml
[[gateway]]
name="ruby"
enable=true
    [[gateway.inout]]
    account="irc.esper"
    channel="#ruby"

    [[gateway.inout]]
    account="discord.obsidian"
    channel="ruby"

    [[gateway.inout]]
    account="api.local"
    channel="api"
```
it seems like the channel is replaced and only works if it is set to api
this **should** be documented at least a little in the sample
especially the fact that it HAS to be set to "api"
or could that be changed ? iit actually does not require any channel.. and it seems that this owuld mess up samechannelgateway as well.. right ?
