### ISSUE TITLE
Starting gateway failed: Bridge failed to start: strconv.ParseInt: parsing "1681142853.025": invalid syntax

### ISSUE THREAD

**Issue by Witherking25** [42wim/matterbridge#2039]
**Describe the bug**
matterbridge crashes with `Starting gateway failed: Bridge discord.emudeck failed to start: strconv.ParseInt: parsing "1681090841.930": invalid syntax`
those random numbers change every time. the dot i assume is what breaks things. every once in a while the dot isn't there and it doesn't break, but if you have multiple gateways, they all have to line up so that it doesn't crash

**To Reproduce**
here's my config
```toml
[general]
RemoteNickFormat="{NICK}@{PROTOCOL} "

[discord.emudeck]
Token="<redacted>"
Server="934078500552462346"
AutoWebhooks=true

[matrix.emudeck]
Server="http://localhost:20662"
Login="emudeck-matterbridge"
Password="<redacted>"
RemoteNickFormat="{NICK}@{PROTOCOL} "
NoHomeServerSuffix=true
HTMLDisable=true
UseUserName=false

[[gateway]]
name="emudeck-updates"
enable=true

[[gateway.inout]]
account="discord.emudeck"
channel="ID:960601621555982336"

[[gateway.inout]]
account="matrix.emudeck"
channel="!ZngaOLJdlWLkUPnduM:matrix.org"

[[gateway]]
name="general"
enable=true

[[gateway.inout]]
account="discord.emudeck"
channel="ID:955837767680655370"

[gateway.inout.options]
WebhookURL="<redacted>"

[[gateway.inout]]
account="matrix.emudeck"
channel="!MjayhstVxXeUgYbQUT:matrix.org"
```

**Expected behavior**

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.

```
[0000]  INFO main:         Running version 1.18.3 8b26e42a
[0000]  INFO router:       Parsing gateway emudeck-updates
[0000]  INFO router:       Parsing gateway general
[0000]  INFO router:       Starting bridge: discord.emudeck 
[0000]  INFO discord:      Connecting
[0000]  INFO discord:      Connecting using token
[0000]  INFO discord:      Connection succeeded
[0000] FATAL main:         Starting gateway failed: Bridge discord.emudeck failed to start: strconv.ParseInt: parsing "1681142853.025": invalid syntax
```

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: 1.18.3 8b26e42a

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))
