### ISSUE TITLE
[api] How to use images in api properly?

### ISSUE THREAD

**Issue by yousefmansy1** [42wim/matterbridge#2052]
**Describe the bug**
Using this site to convert to base 64, I run a sample post with image data and on discord no file is sent at all, and on telegram only a malformed file is sent. (downloading it and changing the extension makes it work as an image again, so the data is fine.)

Original PR, does not have any example. https://github.com/42wim/matterbridge/pull/1993

**To Reproduce**
```bash
DATA=$(cat << EOF
{
	"username": "test",
	"text": "test",
	"gateway": "test",
	"event": "",
	Extra" : {
		"file": [
			{
				"Data": ["BASE64DATA"]
			}
		]
	}
}
EOF

)

curl -XPOST -H 'Content-Type: application/json'  -d "$DATA" http://localhost:4242/api/message#
```

**Expected behavior**
Image should show, but it does not.

**Screenshots/debug logs**
![image](https://github.com/42wim/matterbridge/assets/36427684/06fd51ca-7aa8-4dc8-a02f-bdf0ca762d3c)
![image](https://github.com/42wim/matterbridge/assets/36427684/8db203e7-2e63-40f2-a455-a031db7a1586)

**Environment (please complete the following information):**
 - linux/docker

**Additional context**
```toml
[api]
	[api.myapi]
		BindAddress="172.22.0.111:4242"
		Buffer=1000
		
		
....

[[gateway]]
name="test"
enable=true
	[[gateway.in]]
	account="api.myapi"
	channel="api"
```
