### ISSUE TITLE
Add an asterisk at the end of the editted portion of a message resent to IRC

### ISSUE THREAD

**Issue by derram** [42wim/matterbridge#2060]
This is just a courtesy feature that lines up with how IRC users denote an edit.

**Comment by Mikaela** [comment]
You can already do this either globally or per-account

```toml
[general]
EditSuffix="*"
```
