### ISSUE TITLE
Discord `UseLocalAvatar` option does not work for most users

### ISSUE THREAD

**Issue by lewisakura** [42wim/matterbridge#2098]
**Describe the bug**
The `UseLocalAvatar` option does not apply avatars to most users even when they have associated Discord accounts. We are using Matterbridge in a 30k member Discord server, and upon review of the source code it seems like Matterbridge is only caching a subset of our users (which even then sometimes does not work until ages later). 

**To Reproduce**
Unsure if it's easy to reproduce, see above context.

**Expected behavior**
Matterbridge would request users as needed instead of relying purely on cache.

**Screenshots/debug logs**
![image](https://github.com/42wim/matterbridge/assets/8019327/696f77ce-e84b-4bae-9c87-c1d85155d9d1)

**Environment (please complete the following information):**
 - OS: Oracle Linux Server 8.8 aarch64
 - Self compiled: 56e7bd01ca09ad52b0c4f48f146a20a4f1b78696

**Additional context**
`matterbridge.toml`
```toml
[irc]
    [irc.libera]
    Server="irc.libera.chat:6697"

    UseTLS=true
    SkipTLSVerify=false
    UseSASL=true

    Nick="[redacted]"
    RealName="[redacted]"
    NickServNick="[redacted]"
    NickServPassword="[redacted]"

    ColorNicks=true

    RemoteNickFormat="<{NOPINGNICK}> "

[discord]
    [discord.[redacted]]
    Token="[redacted]"
    Server="[redacted]"

    AllowMention=["users"]
    ShowEmbeds=true

    AutoWebhooks=true
    UseLocalAvatar=["irc.libera"]
    ShowJoinPart=true

    StripNick=true

    RemoteNickFormat="{TENGO}"

    UseUserName=true
    EditSuffix=" (edited)"

[tengo]
RemoteNickFormat="/etc/matterbridge/remotenickformat.tengo"

[[gateway]]
name="[redacted]"
enable=true

    [[gateway.inout]]
    account="irc.libera"
    channel="#[redacted]"

    [[gateway.inout]]
    account="discord.[redacted]"
    channel="[redacted]"
```
`/etc/matterbridge/remotenickformat.tengo`
```go
text := import("text")
result = text.to_lower(nick)
```
