### ISSUE TITLE
(irc <-> discord) Starting gateway failed: Bridge irc failed to start: connection failed dial tcp: lookup hostname: i/o timeout

### ISSUE THREAD

**Issue by mertoalex** [42wim/matterbridge#2156]
> **Describe the bug**

I can't bridge discord <-> irc, it doesn't connects to irc, idk why.

> **To Reproduce**

first I downloaded and opened the source code zip on github, then compiled with:
```bash
┌────(mertoalex  Core2DuoChadbian)-[/tmp/matterbridge-master]
└─$ TAGS="nomsteams,nozulip,noharmony,nohelper,nomatrix,nomattermost,nomumble,nonctalk,norocketchat,noslack,nosshchat,nosteam,notelegram,novk,nowhatsapp,nowhatsappmulti"
┌────(mertoalex  Core2DuoChadbian)-[/tmp/matterbridge-master]
└─$ go build -tags ${TAGS} .
 ``` 
then made config file called test.toml and run it.

> **Expected behavior**

successfully opened and bridged discord <-> irc

> **Screenshots/debug logs**

```bash
┌────(mertoalex  Core2DuoChadbian)-[/tmp/matterbridge-master]
└─$ ./matterbridge -debug -conf test.toml
[0000]  INFO main:         [setupLogger:/tmp/matterbridge-master/matterbridge.go:104] Enabling debug logging.
[0000]  INFO main:         [main:/tmp/matterbridge-master/matterbridge.go:44] Running version 1.26.1-dev 
[0000]  INFO main:         [main:/tmp/matterbridge-master/matterbridge.go:46] WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[0000] DEBUG discord:      [New:/tmp/matterbridge-master/bridge/discord/discord.go:62] Using automatic webhooks
[0000]  INFO router:       [Start:/tmp/matterbridge-master/gateway/router.go:66] Parsing gateway bridge
[0000]  INFO router:       [Start:/tmp/matterbridge-master/gateway/router.go:75] Starting bridge: discord.mydiscord 
[0000]  INFO discord:      [Connect:/tmp/matterbridge-master/bridge/discord/discord.go:70] Connecting
[0000]  INFO discord:      [Connect:/tmp/matterbridge-master/bridge/discord/discord.go:83] Connection succeeded
[0012] DEBUG discord:      [RefreshGuildWebhooks:/tmp/matterbridge-master/bridge/discord/transmitter/transmitter.go:143] Refreshing guild webhooks
[0013] DEBUG discord:      [RefreshGuildWebhooks:/tmp/matterbridge-master/bridge/discord/transmitter/transmitter.go:168] Refreshing guild webhooks using global permission
[0013]  INFO discord:      [assignHooksByAppID:/tmp/matterbridge-master/bridge/discord/transmitter/transmitter.go:255] Picking up webhook channel=[DELETED] id=[DELETED] name=matterbridge 1:21:45AM
[0013]  INFO discord:      [assignHooksByAppID:/tmp/matterbridge-master/bridge/discord/transmitter/transmitter.go:255] Picking up webhook channel=[DELETED] id=[DELETED] name=matterbridge 10:29:43PM
[0013]  INFO discord:      [assignHooksByAppID:/tmp/matterbridge-master/bridge/discord/transmitter/transmitter.go:255] Picking up webhook channel=[DELETED] id=[DELETED] name=matterbridge 10:36:27PM
[0013]  INFO discord:      [assignHooksByAppID:/tmp/matterbridge-master/bridge/discord/transmitter/transmitter.go:255] Picking up webhook channel=[DELETED] id=[DELETED] name=matterbridge 7:53:12PM
[0013]  INFO discord:      [assignHooksByAppID:/tmp/matterbridge-master/bridge/discord/transmitter/transmitter.go:255] Picking up webhook channel=[DELETED] id=[DELETED] name=matterbridge 2:18:53AM
[0013]  INFO discord:      [joinChannels:/tmp/matterbridge-master/bridge/bridge.go:77] discord.mydiscord: joining ID:[DELETED] (ID: ID:[DELETED]discord.mydiscord)
[0013]  INFO router:       [Start:/tmp/matterbridge-master/gateway/router.go:75] Starting bridge: irc.myirc 
[0013]  INFO irc:          [Connect:/tmp/matterbridge-master/bridge/irc/irc.go:81] Connecting irc.oftc.net:6697
[0013] DEBUG irc:          [getClient:/tmp/matterbridge-master/bridge/irc/irc.go:306] setting pingdelay to 1m0s
[0018] ERROR irc:          [doConnect:/tmp/matterbridge-master/bridge/irc/irc.go:194] disconnect: error: dial tcp: lookup irc.oftc.net: i/o timeout
[0018] FATAL main:         [main:/tmp/matterbridge-master/matterbridge.go:66] Starting gateway failed: Bridge irc.myirc failed to start: connection failed dial tcp: lookup irc.oftc.net: i/o timeout
[E] 96: ./matterbridge -debug -conf test.toml
```

> **Environment (please complete the following information):**

 - OS: linux (Debian Unstable)
 - Matterbridge version: 1.26.1-dev
 - If self compiled: yes, I downloaded zip, commit: [d16645c9527a649cc92f3defb865cea9400fa307](https://github.com/42wim/matterbridge/tree/d16645c9527a649cc92f3defb865cea9400fa307)

> **Additional context**

idek if it's about matterbridge or girc too-

test.toml:
```toml
[irc]
[irc.myirc]
Nick="[DELETED]"
UserName="[DELETED]"
Server="irc.oftc.net:6697"
UseTLS=false
SkipTLSVerify=true
RemoteNickFormat="[{NICK} @ {PROTOCOL}]: "

[discord]
[discord.mydiscord]
Token="[DELETED]"
Server="[DELETED]"
AutoWebhooks=true
RemoteNickFormat="[{NICK} @ {PROTOCOL}]: "
PreserveThreading=true
ShowEmbeds=true
ShowJoinPart=true

[[gateway]]
name="bridge"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#test-matterbridge-000000"

[[gateway.inout]]
account="discord.mydiscord"
channel="ID:1180267933130293338"
```
