### ISSUE TITLE
Discord <-> IRC not working in Docker

### ISSUE THREAD

**Issue by ghost** [42wim/matterbridge#2195]
I'm running an Ergochat IRC server and want to bridge it with a Discord server. If I run the matterbridge binary manually, this connection works fine - however with `docker-compose.yaml`, I get one of these errors every time:

- `Bridge irc.atl failed to start: connection failed dial tcp 172.19.0.2:6667: connect: connection refused`
- `Starting gateway failed: Bridge irc.atl failed to start: connection failed EOF`

My docker-compose configuration looks as follows:
```yaml
services:
  ergo:
    init: true
    container_name: ergo
    build: .
    ports:
      - "6667:6667/tcp"
      - "6697:6697/tcp"
    volumes:
      - data:/ircd
      - ./ircd.yaml:/ircd/ircd.yaml:ro
      - ./certs:/ircd/certs:ro
    deploy:
      placement:
        constraints:
          - "node.role == manager"
      restart_policy:
        condition: on-failure
      replicas: 1
    networks:
      - bridge_network

  matterbridge:
    image: 42wim/matterbridge:stable
    container_name: matterbridge
    restart: unless-stopped
    depends_on:
      - ergo
    volumes:
      - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml:ro
    networks:
      - bridge_network

volumes:
  data:

networks:
  bridge_network:
    driver: bridge
```

Here is my matterbridge configuration:
```toml
[discord]
[discord.atl]
Token="<token>"
Server="<server_id>"
AutoWebhooks=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
PreserveThreading=true

[irc]
[irc.atl]
Server="ergo:6667"
Nick="bridge"
NickServNick="bridge"
NickServPassword="<pwd>"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
UseRelayMsg=false
debug=true
ColorNicks=true
JoinDelay=1000
SkipTLSVerify=false
UseSASL=true
RunCommands=["oper bridge <pwd>"]

[[gateway]]
name="general-gateway"
enable=true

	[[gateway.inout]]
	account="discord.atl"
	channel="ID:<channel_id>"
	[[gateway.inout]]
	account="irc.atl"
	channel="#general"
```
