### ISSUE TITLE
Messages to Discord with webhooks enabled ending up in the wrong output channel

### ISSUE THREAD

**Issue by jleclanche** [42wim/matterbridge#239]
Matterbridge version: 1.0.0 (also happened with 0.16.0).

See attached config file at the bottom.
The only issue is with `hearthsim-gateway-hstracker`. Messages sent on gitter.hstracker end up on discord.hearthsim_public **channel hearthsim**, even though they should end up on discord.hearthsim_public **channel hstracker**.

This is a regression from 0.16.0 because of the new Discord webhook system I believe (webhooks are channel-specific, right?).
I think we need more configuration to be able to set up multiple webhooks per channel. Or something. 

cc @saury07

Config file:

```toml
[irc]
[irc.freenode]
Server="chat.freenode.net:6697"
UseTLS=true
UseSASL=true
SkipTLSVerify=false
Nick="TardisBot"
NickServNick="gitter-hearthsim"
NickServPassword="{{ tardisbot_irc_password }}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
MessageQueue=30

[gitter]
[gitter.hearthsim]
Token="{{ tardisbot_gitter_token }}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[discord]

[discord.hearthsim_public]
Token="{{ tardisbot_discord_token }}"
Server="HearthSim Developers"
RemoteNickFormat="[{PROTOCOL}] `{NICK}` "


[[gateway]]
name="hearthsim-gateway-main"
enable=true
	[[gateway.in]]
	account="irc.freenode"
	channel="#hearthsim"

	[[gateway.in]]
	account="gitter.hearthsim"
	channel="HearthSim/HearthSim"

	[[gateway.in]]
	account="discord.hearthsim_public"
	channel="hearthsim"

	[[gateway.out]]
	account="irc.freenode"
	channel="#hearthsim"

	[[gateway.out]]
	account="gitter.hearthsim"
	channel="HearthSim/HearthSim"

	[[gateway.out]]
	account="discord.hearthsim_public"
	channel="hearthsim"


[[gateway]]
name="hearthsim-gateway-hdt"
enable=true
	[[gateway.in]]
	account="gitter.hearthsim"
	channel="HearthSim/Hearthstone-Deck-Tracker"

	[[gateway.in]]
	account="discord.hearthsim_public"
	channel="hdt"

	[[gateway.out]]
	account="gitter.hearthsim"
	channel="HearthSim/Hearthstone-Deck-Tracker"

	[[gateway.out]]
	account="discord.hearthsim_public"
	channel="hdt"


[[gateway]]
name="hearthsim-gateway-hstracker"
enable=true
	[[gateway.in]]
	account="gitter.hearthsim"
	channel="HearthSim/HSTracker"

	[[gateway.in]]
	account="discord.hearthsim_public"
	channel="hstracker"

	[[gateway.out]]
	account="gitter.hearthsim"
	channel="HearthSim/HSTracker"

	[[gateway.out]]
	account="discord.hearthsim_public"
	channel="hstracker"
```
