### ISSUE TITLE
unrecognized import path "code.google.com/p/log4go"

### ISSUE THREAD

**Issue by popey** [42wim/matterbridge#249]
I'm having difficulty building matterbridge from source using go 1.7.6. 

```go get -t -d ./matterbridge.git/...
package code.google.com/p/log4go: unrecognized import path "code.google.com/p/log4go" (parse https://code.google.com/p/log4go?go-get=1: no go-import meta tags)
```

I'm trying to build a matterbridge snap using snapcraft on Ubuntu 16.04. 

Steps to reproduce, on Ubuntu 16.04.

Save the below as ```snapcraft.yaml```, ```apt install snapcraft``` then run ```snapcraft``` in the directory containing the yaml.

```
name: matterbridge
version: '1.0.1'
summary: MatterBridge protocol bridge
description: |
  bridge between mattermost, IRC, gitter, xmpp, slack, discord, telegram,
  rocket.chat, hipchat (via xmpp), steam and matrix with REST API

grade: stable
confinement: devmode

apps:
  matterbridge:
    command: matterbridge
    plugs:
      - network
      - network-bridge

parts:
  go:
    source-tag: go1.7.6
  matterbridge:
    after: [go]
    plugin: go
    source: git://github.com/42wim/matterbridge.git
    source-tag: 'v1.0.1'
    go-importpath: github.com/42wim/matterbridge
```
