### ISSUE TITLE
Telegram reuploading not working well

### ISSUE THREAD

**Issue by erickskrauch** [42wim/matterbridge#300]
### Which version of matterbridge are you using?
`1.4.0`

### Please describe the expected behavior.
In 1.4.0 release was added new cool feature: `telegram: Download files from telegram and reupload to supported bridges (telegram).`

But it actually not working. As I can see in logs files, it just trying to send empty message, but not upload sticker image:

```
time="2017-11-13T14:30:45Z" level=debug msg="Receiving from telegram: &tgbotapi.Message{MessageID:2224, From:(*tgbotapi.User)(0xc4205c6140), Date:1510583445, Chat:(*tgbotapi.Chat)(0xc4208890e0), ForwardFrom:(*tgbotapi.User)(nil), ForwardFromChat:(*tgbotapi.Chat)(nil), ForwardFromMessageID:0, ForwardDate:0, ReplyToMessage:(*tgbotapi.Message)(nil), EditDate:0, Text:"", Entities:(*[]tgbotapi.MessageEntity)(nil), Audio:(*tgbotapi.Audio)(nil), Document:(*tgbotapi.Document)(nil), Game:(*tgbotapi.Game)(nil), Photo:(*[]tgbotapi.PhotoSize)(nil), Sticker:(*tgbotapi.Sticker)(0xc420579000), Video:(*tgbotapi.Video)(nil), VideoNote:(*tgbotapi.VideoNote)(nil), Voice:(*tgbotapi.Voice)(nil), Caption:"", Contact:(*tgbotapi.Contact)(nil), Location:(*tgbotapi.Location)(nil), Venue:(*tgbotapi.Venue)(nil), NewChatMembers:(*[]tgbotapi.User)(nil), LeftChatMember:(*tgbotapi.User)(nil), NewChatTitle:"", NewChatPhoto:(*[]tgbotapi.PhotoSize)(nil), DeleteChatPhoto:false, GroupChatCreated:false, SuperGroupChatCreated:false, ChannelChatCreated:false, MigrateToChatID:0, MigrateFromChatID:0, PinnedMessage:(*tgbotapi.Message)(nil), Invoice:(*tgbotapi.Invoice)(nil), SuccessfulPayment:(*tgbotapi.SuccessfulPayment)(nil)}" module=telegram 
time="2017-11-13T14:30:46Z" level=debug msg="Sending message from ErickSkrauch on telegram.mytelegram to gateway" module=telegram 
time="2017-11-13T14:30:46Z" level=debug msg="Message is config.Message{Text:"", Channel:"-1001088960517", Username:"ErickSkrauch", UserID:"54500107", Avatar:"", Account:"telegram.mytelegram", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"2224", Extra:map[string][]interface {}(nil)}" module=telegram 
time="2017-11-13T14:30:46Z" level=debug msg="ignoring empty message &config.Message{Text:"", Channel:"-1001088960517", Username:"ErickSkrauch", UserID:"54500107", Avatar:"", Account:"telegram.mytelegram", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"2224", Extra:map[string][]interface {}(nil)} from telegram.mytelegram" 
```

We are using Telegram-Discord bridge.

### Please add your configuration file 
```toml
[discord.mydiscord]
 #You can get your token by following the instructions on
 #https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
 #If you want roles/groups mentions to be shown with names instead of ID, 
 #you'll need to give your bot the "Manage Roles" permission.
 Token="xxxxxxxxxxxx"
 Server="xxxxx"
 RemoteNickFormat="**[{NICK}]** "
 
 [telegram.mytelegram]
 #See https://core.telegram.org/bots#6-botfather 
 Token="xxxxxxxxxxx"
 RemoteNickFormat="<{NICK}> "
 #UseInsecureURL=true
 
 [[gateway]]
 name="gateway1"
 enable=true
 
 [[gateway.inout]]
 account="discord.mydiscord"
 channel="xxxxxxxxxx"
 
 [[gateway.inout]]
 account="telegram.mytelegram"
 channel="-xxxxxxxxxxxx"
```
