### ISSUE TITLE
Slack => Slack edits only go to one bridge in complex gateways (with n>2 bridges)

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#342]
:wave: Hiya @42wim!

### Which version of matterbridge are you using?
v1.6.3

### Please describe the expected behavior.

I would expect (when connecting more than 2 slack teams through a single gateway) that an edit/delete in one team would propagate through to all teams.

```toml
# config.toml
[[gateway]]
name="vnetwork"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="vnetwork"
  [[gateway.inout]]
  account="slack.g0vtw"
  channel="vnetwork"
  [[gateway.inout]]
  account="slack.proghacknight"
  channel="vnetwork"
  [[gateway.inout]]
  account="slack.betanyc"
  channel="vnetwork"
```

### Please describe the actual behavior. 

Instead, I am seeing that each edit/delete only gets passed to one other slack team, and the rest don't get the message. Which slack team gets the edit seems to be consistent and reproducible, in that the edit is passed to the next team in some internal list. Edits in A only go to B, edits in B only to C, edits in D only to A, etc.

```
A => B => C => D => A => ...
```

Logs: https://gist.github.com/patcon/c1a34d8d18fdabcfa8111a6458316c90

### Any steps to reproduce the behavior?

Connect 3 slacks and send a message, then edit. Each token is a full user token, not a bot token.

Any suggestions on where to start investigating this? Thanks!
