### ISSUE TITLE
Seems to sync rooms it's not supposed to?

### ISSUE THREAD

**Issue by taoeffect** [42wim/matterbridge#44]
I'm using this to implement a slack<->gitter bridge by using a bot account in Slack and a dedicated GitHub account for Gitter.

So far it works great for syncing two channels together (one on each), but to sync two more channels I'm noticing that the bot will misdirect the message and send it when it's not supposed to.

Here's the setup:

- Initially: slackbot in 1 slack channel, **A1**. gitterbot in 1 gitter channel, **A2**.
- Want to sync another channel (on each network), so I invite the slackbot to another slack channel, **B1**, and join (as the gitterbot) the other gitter channel, **B2** (under the same organization).
- I type a message (as my own user) in the new Slack channel (**B1**), and even though I haven't restarted `matterbridge` or updated it configuration to recognize either of the **B** channels, that message gets relayed into **A2**.

In fact, two messages got relayed into **A2** that shouldn't have been:

```
<gitter> <@U2LRT44TD|gitter> has joined the channel ​
<greg> test ​
```

The first is a notification that I invited the Slack `@gitter` bot to the new channel **B1**, and it's sent to **A2**. The second is the message from **B1** sent to **A2**.

Neither of those messages should have been relayed, as the `.toml` wasn't even setup to support the new **B** channels.

Here's the end of my `.toml`, and I'm using the latest 0.7.0-dev build from `master` at commit db0e4ba:

```toml
[[gateway]]
#OPTIONAL (not used for now)
name="gateway1"
#Enable enables this gateway
##OPTIONAL (default false)
enable=true

    #[[gateway.in]] specifies the account and channels we will receive messages from.
    #The following example bridges between mattermost and irc
    [[gateway.in]]

    #account specified above
    #REQUIRED
    account="slack.groupincome"
    #channel to connect on that account
    #REQUIRED
    channel="groupincome"

    [[gateway.in]]
    account="gitter.groupincome"
    channel="okTurtles/group-income"

    [[gateway.out]]
    account="slack.groupincome"
    channel="groupincome"

    [[gateway.out]]
    account="gitter.groupincome"
    channel="okTurtles/group-income"
```

Note that the above shows the configuration for **A1** and **A2**.
