### ISSUE TITLE
api improvements

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#459]
**Is your feature request related to a problem? Please describe.**

I want to use multiple applications using the matterbridge api, and setting up new api endponts to be less of a chore,
in my casei want to run at least one bot constantly on a gateway and then connect up to 4 more apps from my dev environment.. or maybe morei n the future,
at the moment i have to manually add new api sections and entries in the gateways for each of them

**Describe the solution you'd like**

All applications connect to one api on the same part and distinguish between each other either by using different endpoints

eg. `GET /api/messages/myapp1 `,  `GET /api/stream/myapp1 ` and `POST /api/message/myapp1`  
(btw maybe use message**s** for both endpoints ?)

**Additional context**

sample config:
```
[[gateway.inout]]
account="api.local"
channel="api" 
application="myapp1"
```
leaving application empty would mean all applications send / receive there

**alternatives**

an alternative would be to keep the same endpoints but have a field for the application name in the json objects exanged between api and application
```json
{
  "text":"blah",
  "application":"myapp1"
}
```

**Comment by patcon** [comment]
What about this:

- `application` acts as an alias for `channel`
- `channel`/`application` becomes required

```toml
[[gateway]]
  name="test-gateway"
  enable=true
  [[gateway.inout]]
    account="slack.test"
    channel="general"
  [[gateway.inout]]
    account="api.local"
    channel="myapp1" # or `application`
  [[gateway.inout]]
    account="api.local"
    application="myapp2" @ or `channel`
```

And then you can send messages in various ways:

1. `POST /api/messages`

```json
{
  "gateway": "test-gateway"
  "text": "this is a test message",
  "username": "some-user"
  "application": "myapp1"
}
```

2. `POST /api/gateways/:gateway/applications/:app/messages`

`POST /api/gateways/test-gateway/applications/myapp2/messages`

```json
  "text": "this is a test message",
  "username": "some-user"
```

Baaaaasically:
- if it's not in the url, it must be in the payload.
- channel == application

Would that work for you?

Note: this would also leave things in good shape to flesh the API out into a proper RESTful api at some point, eg. `GET /api/gateways` lists all gateways, `PUT /api/gateways/test-gateway` allows modifying gateway, etc.
