### ISSUE TITLE
Using webhook for discord breaks functionality

### ISSUE THREAD

**Issue by Jaykul** [42wim/matterbridge#462]
**Describe the bug**
When we use a token for a discord connection there are features which do not work at all when using a webhook instead (and vice-versa).

Specifically, the **token**:
1. Allows uploading images (if I post an image on slack, it shows up in discord)
2. Allows editing messages (if I edit a message on slack, the original message in discord is edited).

While the **webhook**:
1. Allows the nick and avatar of the bot to change to match the sender

But when I have the token configured for the service, and the webhook for the channel, I only get the webhook features.

**To Reproduce**
Using latest docker image (42wim/matterbridge:1.11.0) configure something like this:

```toml
[general]
RemoteNickFormat="{NICK} ({PROTOCOL})"
EditSuffix=" (edited)"
IconURL="https://robohash.org/{NICK}.png?set=set4"

[discord]
    [discord.powershell]
    Label="dc"
    Token="a.discord.token"
    Server="PowerShell"

[slack]
    [slack.powershell]
    Label="sk"
    Token="xoxb-a-slack-token"
```

And add a channel with a webhookurl for discord:

```toml
[[gateway]]
name="poshcode"
enable=true

    [[gateway.inout]]
    account="slack.powershell"
    channel="poshcode"

    [[gateway.inout]]
    account="discord.powershell"
    channel="poshcode"
        [gateway.inout.options]
        webhookurl="https://discordapp.com/api/webhooks/yourserverid/yourchannelhook"
```

**Expected behavior**
Ideally, I'd like the nick and avatar to change, but still have screenshots uploaded to discord, and edits to messages show up as edits instead of posted as new messages ...

**Screenshots/debug logs**
I can provide more if necessary ... but I believe this will be easy to reproduce.

**Environment:**
 - OS: linux running in kubernetes in azure 😉 
 - "Running version 1.11.0 6f13125" prefix=main
