### ISSUE TITLE
disallow @everyone and @here in discord

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#476]
**Is your feature request related to a problem? Please describe.**
`@everyone` and `@here` are not configurable to be filtered when sent to discord
a bot user can be configured to being disallowed to ping everyone,
but there is no such setting when using webhooks

**Describe the solution you'd like**
confiig entries
```toml
allowPingEveryone=false # default false
allowPingHere=false # default true
allowPingUser=false # default true
```

also related to #460 for translating user mentions

possibly also 
```toml
IgnorePing="someUser someOther Bot.+"
```
similar to `IgnoreMessages`

**Describe alternatives you've considered**
I have tried to filter it through `IgnoreMessages`, but that does not work for messages coming in from api endpoints
and there is no general setting for `IgnoreMessages` that that applies to every platform
