### ISSUE TITLE
Bridge doesn't work within a single team

### ISSUE THREAD

**Issue by akhmerov** [42wim/matterbridge#48]
Not sure if it is a bug at all, but for a reference the following bridge configuration results in no messages being sent at all:

```toml
[[gateway.in]]
account="mattermost1"
channel="channel1"

[[gateway.in]]
account="mattermost1"
channel="channel2"

[[gateway.out]]
account="mattermost1"
channel="channel1"

[[gateway.out]]
account="mattermost1"
channel="channel2"
```

Since there is hardly a relevant use case (private discussion while commenting on a public one, perhaps??), it doesn't seem to be important.
