### ISSUE TITLE
1.11 is not posting image urls from slack

### ISSUE THREAD

**Issue by Jaykul** [42wim/matterbridge#483]
**Describe the bug**
When I paste an image or upload a file on the slack side, only the "comment" shows up on the discord side, and if there's no comment -- there's no message at all

**To Reproduce**

1. Configure discord or IRC 
2. Configure slack with a token
3. Post an image on the slack side without a comment

... nothing happens on slack.

**Expected behavior**
We _used to get_ slack image URLs (with a space missing) that had to be clicked and you needed a login, but at least we'd know someone had posted an image and could tell them to use imgur instead.

**Config Example**
```toml
[general]
RemoteNickFormat="{NICK} ({LABEL})"
EditSuffix=" (edited)"
IconURL="https://robohash.org/{NICK}.png?set=set4"
ReplaceMessages=[ ["@everyone","~everyone"], ["@here","~here"] ]

[discord]
    [discord.powershell]
    Label="discord"
    Token="..."
    Server="PowerShell"

[slack]
    [slack.powershell]
    Label="ps"
    Token="xoxb-..."
[irc]
    [irc.freenode]
    Label="irc"
    Server="irc.freenode.net:7000"
    UseTLS=true
    Nick="bifrost"
    UseSASL=true
    NickServNick="bifrost"
    NickServPassword="..."
    ColorNicks=true
    RemoteNickFormat="({PROTOCOL}) <{NOPINGNICK}> "
    EditDisable=true

[[gateway]]
name="bridge"
enable=true

    [[gateway.inout]]
    account="slack.powershell"
    channel="bridge"

    [[gateway.inout]]
    account="irc.freenode"
    channel="#PowerShell"

    [[gateway.inout]]
    account="discord.powershell"
    channel="bridge"
        [gateway.inout.options]
        webhookurl="https://discordapp.com/api/webhooks/...."
```
