### ISSUE TITLE
Message echoing in a mattermost1 <-> mattermost2 bridge

### ISSUE THREAD

**Issue by akhmerov** [42wim/matterbridge#49]
A bridge between different teams results in each message repeated in the channel from which it had originated.

```toml
[mattermost]
    [mattermost1]
    useAPI=true
    Server="yourmattermostserver.domain"
    Team="yourteam1"
    Login="yourlogin"
    Password="yourpass"
    PrefixMessagesWithNick=true

    [mattermost2]
    useAPI=true
    Server="yourmattermostserver.domain"
    Team="yourteam2"
    Login="yourlogin"
    Password="yourpass"
    PrefixMessagesWithNick=true

[[gateway.in]]
account="mattermost1"
channel="channel1"

[[gateway.in]]
account="mattermost2"
channel="channel2"

[[gateway.out]]
account="mattermost1"
channel="channel1"

[[gateway.out]]
account="mattermost2"
channel="channel2"
```

Every time a user sends a message in `yourteam1/channel1`, the bot outputs it both in `yourteam2/channel2` as well as `yourteam1/channel1` (expected behavior would result in output only in `yourteam2/channel2`).
