### ISSUE TITLE
When restarting matterbridge discord nicknames are forgotten

### ISSUE THREAD

**Issue by mralext20** [42wim/matterbridge#504]
**To Reproduce**
set a nickname on a discord server
restart the matterbridge 
send a message on discord

**Expected behavior**
matterbridge should find out what someone's nickname is on startup or on their first message.

**Screenshots/debug logs**
![screenshot 2018-09-23 11-28-42](https://user-images.githubusercontent.com/4016295/45932123-4c062880-bf24-11e8-98f6-5d3f472a946f.png)

**Environment (please complete the following information):**
 - OS: Linux, running in docker
 - Matterbridge version: 1.11.4-dev 1fe81b7

**Additional context**
```toml
[discord.mk]
Token="DISCORD TOKEN"
RemoteNickFormat="<{NICK}>: "

[slack.mk]
Token="SLACK TOKEN"
RemoteNickFormat="{NICK}"

[general]
MediaDownloadSize=8000000

[[gateway]]
name="general"
enable=true

    [[gateway.inout]]
    account="discord.mk"
    channel="ID:486747538376884257"

    [[gateway.inout]]
    account="slack.mk"
    channel="general"


[[gateway]]
name="random"
enable=true

    [[gateway.inout]]
    account="discord.mk"
    channel="ID:486747772599664650"

    [[gateway.inout]]
    account="slack.mk"
    channel="random"


[[gateway]]
name="programming"
enable=true
    [[gateway.inout]]
    account="discord.mk"
    channel="ID:486747851024498698"

    [[gateway.inout]]
    account="slack.mk"
    channel="programmers"

[[gateway]]
name="builders"
enable=true
    [[gateway.inout]]
    account="discord.mk"
    channel="ID:486747870364434453"

    [[gateway.inout]]
    account="slack.mk"
    channel="builders"


[[gateway]]
name="pictures"
enable=true
    [[gateway.inout]]
    account="discord.mk"
    channel="ID:488942247543439361"

    [[gateway.inout]]
    account="slack.mk"
    channel="pictures"

[[gateway]]
name="business"
enable=true
    [[gateway.inout]]
    account="discord.mk"
    channel="ID:486747888689610772"

    [[gateway.inout]]
    account="slack.mk"
    channel="business"

```

**Comment by mralext20** [comment]
docker-compose.yml:
```yml
version: '3'
services:
    matterbridge:
        restart: unless-stopped
        volumes:
            - ${PWD}/matterbridge.toml:/matterbridge.toml
        image: 42wim/matterbridge
```
