### ISSUE TITLE
Allow Protocol-level config to be set on the Gateway

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#621]
Lots of the protocol struct config could be helpful to be able to set at the gateway level. For example, would be great if we could do things like this:

```toml
[general]
SyncTopic=true

[slack.myteam]
Token="xxxxxx"

[[gateway]]
  name="testing"
  enable=true
  SyncTopic=false
  [[gateway.inout]]
    account="slack.myteam"
    channel="foo-channel"
  [[gateway.inout]]
    account="slack.myteam"
    channel="bar-channel"
```
