### ISSUE TITLE
Bot silently fails and not does bridge messages between IRC and Slack

### ISSUE THREAD

**Issue by jwflory** [42wim/matterbridge#642]
# Description

Bot successfully starts and claims to join IRC channels, but:

1. Only 1-2 IRC channels are successfully joined
2. Bridging from either Slack or IRC does not work
3. Bot eventually quits from IRC and never comes back (even when running)
4. No logs indicate anything is wrong

# To reproduce

Run the bot with [this config](https://github.com/FOSSRIT/infrastructure/blob/253d54ce19fc9570e276bfec789f1a7c1b29d398/roles/matterbridge/templates/matterbridge.toml) and [these variables](https://github.com/FOSSRIT/infrastructure/blob/253d54ce19fc9570e276bfec789f1a7c1b29d398/roles/matterbridge/vars/main.yml):

```toml
###################################################################
#IRC section
###################################################################

[irc]
[irc.{{ default_irc_network_name }}]
Server="{{ default_irc_network_server }}"
UseTLS=true
SkipTLSVerify=false
UseSASL=false
Nick="{{ default_irc_bot_nick }}"

MessageSplit=true
ColorNicks=true
IgnoreNicks="{{ default_irc_ignore_nicks }}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
ShowJoinPart=true
ShowTopicChange=true


###################################################################
#slack section
###################################################################
[slack]
[slack.{{ default_slack_team_name }}]
Token="{{ default_slack_api_token }}"

IconURL="https://robohash.org/{NICK}.png?size=48x48"
EditSuffix=" (edited)"
PrefixMessagesWithNick=false
IgnoreNicks="{{ default_slack_ignore_nicks }}"

PreserveThreading=true


###################################################################
#General configuration
###################################################################

[general]
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "


###################################################################
#Gateway configuration
###################################################################

[[gateway]]
name="gateway_rit"
enable=true

    [[gateway.inout]]
    account="irc.{{ default_irc_network_name }}"
    channel="{{ matterbridge_config.rit.irc.channel }}"

    [[gateway.inout]]
    account="slack.{{ default_slack_team_name }}"
    channel="{{ matterbridge_config.rit.slack.channel }}"

[[gateway]]
name="gateway_rit_foss"
enable=true

    [[gateway.inout]]
    account="irc.{{ default_irc_network_name }}"
    channel="{{ matterbridge_config.rit.irc.channel }}"

    [[gateway.inout]]
    account="slack.{{ default_slack_team_name }}"
    channel="{{ matterbridge_config.rit.slack.channel }}"
```

# Expected behavior

1. Start bot (`/usr/local/bin/matterbridge -conf matterbridge.toml`)
2. Bot successfully starts
3. Messages from Slack go to IRC, IRC messages go to Slack

# Debug logs

More information is also in FOSSRIT/infrastructure#21.

```
/usr/local/bin/matterbridge -debug -conf matterbridge.toml 
[0000]  INFO main:         Enabling debug
[0000]  INFO main:         Running version 1.12.1 d2cfd23
[0000]  INFO gateway:      Parsing gateway gateway_ritlug_teleirc
[0000]  INFO gateway:      Parsing gateway gateway_rit
[0000]  INFO gateway:      Parsing gateway gateway_rit_foss
[0000]  INFO gateway:      Parsing gateway gateway_rit_lug_sysadmin
[0000]  INFO gateway:      Parsing gateway gateway_rit_tigeros
[0000]  INFO gateway:      Parsing gateway gateway_ritlug
[0000]  INFO gateway:      Starting bridge: irc.freenode 
[0000]  INFO irc:          Connecting irc.freenode.net:6697
[0000] DEBUG irc:          "CLIENT_INIT :irc.freenode.net:6697"
[0000] DEBUG irc:          ":asimov.freenode.net NOTICE * :*** Looking up your hostname..."
[0000] DEBUG irc:          ":asimov.freenode.net NOTICE * :*** Checking Ident"
[0000] DEBUG irc:          ":asimov.freenode.net NOTICE * :*** No Ident response"
[0000] DEBUG irc:          ":asimov.freenode.net NOTICE * :*** Found your hostname"
[0000] DEBUG irc:          ":asimov.freenode.net CAP * LS :account-notify extended-join identify-msg multi-prefix sasl"
[0000] DEBUG irc:          ":asimov.freenode.net CAP slack-ritlug ACK :account-notify extended-join multi-prefix "
[0000] DEBUG irc:          ":asimov.freenode.net 001 slack-ritlug :Welcome to the freenode Internet Relay Chat Network slack-ritlug"
[0000] DEBUG irc:          "CLIENT_GENERAL_UPDATED"
[0000] DEBUG irc:          Registering callbacks
[0000] DEBUG irc:          "CLIENT_GENERAL_UPDATED"  # this is repeated for many, many lines
[ ... ]
[0002] DEBUG irc:          "CLIENT_CONNECTED :irc.freenode.net:6697"
[0005] DEBUG irc:          ":slack-ritlug MODE slack-ritlug :+Zi"
[0005]  INFO irc:          Connection succeeded
[0005]  INFO bridge:       irc.freenode: joining #ritlug (ID: #ritlugirc.freenode)
[0005]  INFO bridge:       irc.freenode: joining #ritlug-teleirc (ID: #ritlug-teleircirc.freenode)
[0005] DEBUG irc:          handle girc.Event{Source:(*girc.Source)(0xc0007a4840), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xbef9819888fc1765, ext:5859984620, loc:(*time.Location)(0x18436a0)}, Command:"JOIN", Params:[]string{"#ritlug", "*"}, Trailing:"slack-ritlug", EmptyTrailing:false, Sensitive:false, Echo:false}
[0005] DEBUG irc:          333: Topic set by jwf|matrix [jflory7mat@rit/foss/captain/fedora.jflory7] [2018-06-29 21:12:09 -0400 EDT]
[0029] DEBUG irc:          == Receiving PRIVMSG: jwf slack-ritlug: ?? girc.Event{Source:(*girc.Source)(0xc000731bf0), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xbef9819e5fb2f0be, ext:29241066566, loc:(*time.Location)(0x18436a0)}, Command:"PRIVMSG", Params:[]string{"#ritlug"}, Trailing:"slack-ritlug: ??", EmptyTrailing:false, Sensitive:false, Echo:false}
[0029] DEBUG irc:          detected UTF-8 confidence 10
[0029] DEBUG irc:          <= Sending message from #ritlug on irc.freenode to gateway
```

Nothing happens after this message. Even when other activity on either side of the bridge happens, there is silence.

## Environment

 - **OS**: Linux, CentOS 7.5
 - **Matterbridge version**: 1.12.1 d2cfd23
