### ISSUE TITLE
Add Translation ability to bridge

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#647]
Re-ticketed from: https://github.com/42wim/matterbridge/pull/512

I feel like I've learned a bit about how the app (and Go) works in the time since I first started that ticket.

Wanted to make a fresh ask, after using translation for quite some time.

- In the old feature branch, we're translating each language on the fly. This takes quite some time for each, and it's done for each msg, after the router starts looping through all destination channels.
- It feels like it would be most effective to instead check for every language used before iterating over channels, and then do the minimal number of translation API calls to create the base translations.

My current imagining is that we're talking about a config like this:

```toml
[[gateway]]
  name="test-gateway"
  enable=true
  # main international slack
  [[gateway.inout]]
    account="slack.team-main"
    channel="test-channel"
  [[gateway.inout]]
    account="slack.team-main"
    channel="test-channel-zh"
    [gateway.inout.options]
      locale="zh"
  [[gateway.inout]]
    account="slack.team-main"
    channel="test-channel-en"
    [gateway.inout.options]
      locale="en"
  [[gateway.inout]]
    account="slack.team-main"
    channel="test-channel-ja"
    [gateway.inout.options]
      locale="ja"
  [[gateway.inout]]
    account="slack.team-main"
    channel="test-channel-ko"
    [gateway.inout.options]
      locale="ko"
  # separate country slacks
  [[gateway.inout]]
    account="slack.team-japan"
    channel="test-channel"
    [gateway.inout.options]
      locale="ja"
  [[gateway.inout]]
    account="slack.team-korea"
    channel="test-channel"
    [gateway.inout.options]
      locale="ko"
  [[gateway.inout]]
    account="slack.team-canada"
    channel="test-channel"
    [gateway.inout.options]
      locale="en"
```

Note that each language gets translated a few times. It would be great to iterate over the config, find all the candidate languages, and do a minimal number of API calls, then storing the raw translations in `Extra`. I am currently imagining a couple options, either involving serialization or not:
1. ```go
    Extras["translation_en"][0] = "lorem ipsem etc"
    ```
2. ```go
    Extras["translations"][0] = `{"en": "lorem ipsum etc"}`
    Extras["translations"][1] = `{"fr": "le lorem ipsum etc"}`
    ```
3. ```go
    Extras["translations"][0] = `{en": "lorem ipsum etc", "fr": "le lorem ipsum etc"}`
    ```

Any feelings on which one is better? Also, I think we need a place to store the original language. Would that be `Extras["original language"][0]`? And if so, it seems that storing arbitrary values will always require a little Get'ing and Set'ing in extras, and I'm wondering if we could add some helper functions on `Message` instances for making this simpler.

Thanks for any feedback before I jump into this rewrite!
