### ISSUE TITLE
Gitter bridge breaks after a while

### ISSUE THREAD

**Issue by taoeffect** [42wim/matterbridge#703]
**Describe the bug**

Seeing this in our log:

```
time="2019-02-05T22:22:02-08:00" level=info msg="Starting bridge: slack.groupincome " prefix=gateway
time="2019-02-05T22:22:02-08:00" level=info msg="Connecting using token" prefix=slack
time="2019-02-05T22:22:02-08:00" level=info msg="slack.groupincome: joining groupincome (ID: groupincomeslack.groupincome)" prefix=bridge
time="2019-02-05T22:22:03-08:00" level=info msg="Starting bridge: gitter.groupincome " prefix=gateway
time="2019-02-05T22:22:03-08:00" level=info msg=Connecting prefix=gitter
time="2019-02-05T22:22:03-08:00" level=info msg="Connection succeeded" prefix=gitter
time="2019-02-05T22:22:03-08:00" level=info msg="gitter.groupincome: joining okTurtles/group-income (ID: okTurtles/group-incomegitter.groupincome)" prefix=bridge
time="2019-02-05T22:22:04-08:00" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main
time="2019-02-05T22:41:24-08:00" level=error msg="connection with gitter closed for room okTurtles/group-income" prefix=gitter
time="2019-02-05T22:42:18-08:00" level=error msg="Connection failed "dial tcp 18.207.50.150:443: i/o timeout" &net.OpError{Op:"dial", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc420473950), Err:(*poll.TimeoutError)(0x74675405580)}" prefix=slack
```

It initially works and then stops.

Using version 1.12.3.

Our `matterbridge.toml` looks like this:

```toml
[gitter]
[gitter.groupincome]
Token="[token]"
RemoteNickFormat="<{NICK}> "

[slack]
[slack.groupincome]

Token="[token]"
PrefixMessagesWithNick=true
RemoteNickFormat="<{NICK}> "
NickFormatter="plain"
NicksPerRow=4
EditSuffix=" (edited)"

[[gateway]]
name="gateway1"
enable=true

    [[gateway.inout]]
    account="slack.groupincome"
    channel="groupincome"

    [[gateway.inout]]
    account="gitter.groupincome"
    channel="okTurtles/group-income"
```
