### ISSUE TITLE
Rocket.Chat → Discord edits all messages and stops working when bridging multiple channels

### ISSUE THREAD

**Issue by Epicpkmn11** [42wim/matterbridge#745]
**Describe the bug**
I'm trying to bridge Rocket.Chat <-> Discord, but if I try to bridge multiple channels it edits every message and after a bit stops sending... Bridging just one channel seems to work fine.

**To Reproduce**
1. Set up a Rocket.Chat <-> Discord bridge on more that one channel, either using `samechannelgateway` or multiple `gateway`s.
2. Run matterbridge
3. It edits every message from RC → Discord, and stops working after a bit, especially if a lot of messages are sent

**Expected behavior**
3. It only edits messages that are actually edited, and doesn't stop after a bit

**Screenshots/debug logs**
![2019-02-27 22 53 22](https://user-images.githubusercontent.com/41608708/53542100-7fa43a80-3ae2-11e9-9645-962ec1239ee0.png)
(↑ Not edited | ↓ Edited)
![2019-02-27 22 51 29](https://user-images.githubusercontent.com/41608708/53542040-3e138f80-3ae2-11e9-8846-bbbd8f95435d.png)

**Environment (please complete the following information):**
 - OS: I've run it on both my MacBook Air 6,2 (macOS 10.14.3) and Raspberry Pi 2 B (Running the Rocket.Chat server, some kind of Raspbian)
 - Matterbridge version: version: 1.14.0-rc1 516fd3c (On both)

**Additional context**
My config:
```toml
[rocketchat]
[rocketchat.dshb]
#The rocketchat hostname. (prefix it with http or https)
#REQUIRED (when not using webhooks)
Server="https://dshomebrew.serveo.net"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
#REQUIRED (when not using webhooks)
Login="[The bot account's email]"
Password="[The bot account's password]"

PrefixMessagesWithNick=true

[discord]
[discord.tmh]
Token="[The bot's token]"
Server="TWL Mode Hacking!"

[general]
RemoteNickFormat="<{NICK}> "

[[gateway]]
    name = "general"
    enable=true

    [[gateway.inout]]
    account = "discord.tmh"
    channel="general"

    [[gateway.inout]]
    account ="rocketchat.dshb"
    channel = "general"

[[gateway]]
    name = "offtopic"
    enable=true

    [[gateway.inout]]
    account = "discord.tmh"
    channel="offtopic"

    [[gateway.inout]]
    account ="rocketchat.dshb"
    channel = "offtopic"
```

Sorry for making an Issue if I'm just doing something wrong, or if this feature just isn't ready yet (Rocket.Chat using a bot account appears to be since the last release, right?), but if you've got any idea what I'm doing wrong, help would be appreciated 😃
