### ISSUE TITLE
Interested in other protocols?

### ISSUE THREAD

**Issue by jleclanche** [42wim/matterbridge#9]
Hi

I've been designing a gitter/irc bridge that would work much like matterbridge. I use gitter-irc-bot for mirroring channels and it doesn't support multiple bridges per instance.

I wrote a prototype here in python:
https://github.com/jleclanche/gitterway

My idea was to allow multiple protocols, including the possibility of writing your own protocol plugin eventually. I wrote another prototype in go (which I think is better for this task), with the config in toml looking something like this:

```toml
[gitter]
	# Your gitter accounts

	[gitter.hsimbot]
	apikey = "..."

	[gitter.helixbot]
	apikey = "..."

[irc]
	# Your IRC accounts

	[irc.helixbot]
	server = "chat.freenode.net"
	port = 6697
	nick = "HelixBot"


# Define your gateways below
[[gateway]]
	name = "hearthsim"
	in = [
		{ account = "gitter.hsimbot", channel = "hearthsim/hearthsim" },
		{ account = "irc.helixbot", channel = "#hearthsim" },
	]
	out = [
		{ account = "gitter.hsimbot", channel = "hearthsim/hearthsim" },
		{ account = "irc.helixbot", channel = "#hearthsim" },
	]

[[gateway]]
	name = "letsauth"
	in = [
		{ account = "gitter.helixbot", channel = "letsauth/letsauth" },
		{ account = "irc.helixbot", channel = "#letsauth" },
	]
	out = [
		{ account = "gitter.helixbot", channel = "hearthsim/hearthsim" },
		{ account = "irc.helixbot", channel = "#hearthsim" },
	]
```

I'd like to expand this to gitter, slack and mattermost, possibly some other protocols ([Matrix](https://vector.im/beta/)?). This is similar to what [Sameroom](https://sameroom.io/) does. Anyway, wondering if you're interested in all this, your code looks great right now.
