### ISSUE TITLE
Links get corrupted

### ISSUE THREAD

**Issue by HarHarLinks** [42wim/matterbridge#924]
**Describe the bug**
Certain kind of link gets corrupted/misformatted bridging slack (new bot variant) to matrix.
Specifically one of the double dashes (minus signs) gets deleted and the link will only be formatted until the character before the dashes. Link is fine inside slack (website).

**To Reproduce**
Send a onedrive share link from slack to matrix.

**Expected behavior**
Working link formatting

**Screenshots/debug logs**
![image](https://user-images.githubusercontent.com/2803622/67444743-a59ac400-f60a-11e9-8036-748de7498d26.png)
```json
{
  "type": "m.room.message",
  "sender": "@matterbridge:myserver.tld",
  "content": {
    "msgtype": "m.text",
    "body": "[slack] <Max> https://1drv.ms/w/s!Anfsv--MQXXXXXXXXXXXXXHi1",
    "format": "org.matrix.custom.html",
    "formatted_body": "[slack] &lt;Max&gt; <a href=\"https://1drv.ms/w/s!Anfsv\">https://1drv.ms/w/s!Anfsv</a>–MQXXXXXXXXXXXXHi1"
  },
  "origin_server_ts": 1571844253877,
  "unsigned": {
    "age": 3716119
  }
}
```

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 9.11 (stretch) (GNU/Linux 4.19.0-0.bpo.5-amd64 x86_64 )
 - Matterbridge version: version: 1.15.1 87788f3

**Additional context**
```toml
[matrix.myserver]
Server="https://myserver.tld"
Login="matterbridge"
Password=
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
NoHomeServerSuffix=true

[slack.server]
Token="xoxb-"
RemoteNickFormat="{NICK}"

[[gateway]]
name="gateway"
enable=true

[[gateway.inout]]
account="slack.server"
channel="channel"

[[gateway.inout]]
account="matrix.myserver"
channel="#room:myserver.tld"
```
