### ISSUE TITLE
Attachments Slack -> Matrix not relayed

### ISSUE THREAD

**Issue by HarHarLinks** [42wim/matterbridge#925]
**Describe the bug**
A pdf file sent on slack is not forwarded to matrix. File size does not exceed upload limit by far.
Slack: new bot setup variant.

>that support native file uploads (Discord,Matrix,Mattermost,Slack,Telegram,Rocketchat) will receive a uploaded copy of the file from protocols that have links to files with authentication (Matrix, Mattermost, Slack, Telegram)

Is this to be expected? Do I need to configure a file server to enable file forwarding even though it should not be used in this case as native is possible?

**To Reproduce**
Send pdf in slack room bridged to matrix room.

**Expected behavior**
File gets uploaded to matrix.

**Screenshots/debug logs**
Does not appear in normal log, going to try out debug log.
No indication of file upload in matrix server log.

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 9.11 (stretch) (GNU/Linux 4.19.0-0.bpo.5-amd64 x86_64 )
 - Matterbridge version: version: 1.15.1 87788f3

**Additional context**
```toml
[matrix.myserver]
Server="https://myserver.tld"
Login="matterbridge"
Password=
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
NoHomeServerSuffix=true

[slack.server]
Token="xoxb-"
RemoteNickFormat="{NICK}"

[[gateway]]
name="gateway"
enable=true

[[gateway.inout]]
account="slack.server"
channel="channel"

[[gateway.inout]]
account="matrix.myserver"
channel="#room:myserver.tld"
```
