### ISSUE TITLE
Incorrect relay of a message from gitter to mattermost

### ISSUE THREAD

**Issue by akhmerov** [42wim/matterbridge#956]
**Describe the bug**
The following message on gitter:

![image](https://user-images.githubusercontent.com/2069677/70154361-abc39c00-16b0-11ea-9864-c1799a69af6a.png)

[source here](https://gitter.im/python-adaptive/adaptive?at=5de7b66b9319bb5190de945e)

Was relayed to mattermost as:

![image](https://user-images.githubusercontent.com/2069677/70154480-d877b380-16b0-11ea-9c23-b0ae4e5686ae.png)

(i.e. the end of the message was truncated)

Trying to send the exact same message again resulted in the correct behavior, and therefore I cannot reproduce the issue, sorry :(

**Environment (please complete the following information):**
 - Matterbridge docker image running version 1.16.2 214fe50, image 659df2a1a43c

**Additional context**

Relevant config:

```toml
[mattermost]

[mattermost.qt]

Team="chat"
Login="{{ bot_login }}"
IgnoreNicks="relaybot"

Server="{{ bot_server }}"
Password="{{ bot_password }}"
PrefixMessagesWithNick=true
RemoteNickFormat="**{NICK}:** "

[gitter]
[gitter.kwant]
Token="{{ gitter_kwant_bot_token }}"
PrefixMessagesWithNick=true
RemoteNickFormat="*{NICK}:*\n"

[[gateway]]
enable=true
name="adaptive-channel"

[[gateway.inout]]
account="mattermost.qt"
channel="adaptive-evaluation"
[[gateway.inout]]
account="gitter.kwant"
channel="python-adaptive/adaptive"
```
