### ISSUE TITLE
Using Discord with user account fails

### ISSUE THREAD

**Issue by haykam821** [42wim/matterbridge#972]
When the token supplied to Discord is for a user account, Matterbridge fails with the following error message:

```
Error obtaining server members: HTTP 403 Forbidden, {"message": "Missing Access", "code": 50001}
```

Here is the config used, with secret values substituted:

```toml
[discord.personal]
Token="User <DISCORD_TOKEN>"
RemoteNickFormat=""
Server="<DISCORD_SERVER>"

[telegram.personal]
Token="<TELEGRAM_TOKEN>"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway"
enable=true

[[gateway.inout]]
account="discord.personal"
channel="<DISCORD_CHANNEL>"

[[gateway.inout]]
account="telegram.personal"
channel="<TELEGRAM_CHANNEL>"
```
